### ISSUE TITLE
Picking up mop by clicking doesn't work when not already standing next to it

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#10]
When clicking on the mop to pick it up, the character will just walk next to it. Only from this exact position (without moving any further) another click on the mop will pick it.
![grafik](https://user-images.githubusercontent.com/17579552/115997640-2235a680-a5e4-11eb-82d4-c79caeab10f2.png)

**Comment by jhovgaard** [comment]
I believe this was fixed by the mouse controller update. @Gerwanese can you confirm?

**Comment by Gerwanese** [comment]
Confirmed, works now.
