### ISSUE TITLE
Opening Voogle Maps while holding arrow key causes map to move

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#100]
Build 49

When opening Voogle Maps (through "M" or clicking the button doesn't matter) while holding any of the arrow keys, the map will be slowly moving into that direction.
It can be stopped by pressing the opposite direction arrow button.
This can be a bit annoying while driving car.

https://user-images.githubusercontent.com/17579552/120248678-7c2b2b00-c278-11eb-9394-8cf6400127ca.mp4

**Comment by jokoho48** [comment]
Fixed in Build 190 (or when ever the new CitymapCamera got added)
