### ISSUE TITLE
Dragging on Voogle Maps opens building overlay

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#101]
Build: 49

When dragging Voogle Maps around, the building overlay will show up if the starting point of dragging was on a building (which happens more easily as more buildings come).

https://user-images.githubusercontent.com/17579552/120248779-d4622d00-c278-11eb-8529-c38575490092.mp4

**Comment by jokoho48** [comment]
Fixed in Build 186
