### ISSUE TITLE
Cars can't get "out of world" anymore and are stuck

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#102]
Build 49

As a result of your bugfix for #44, now cars can't get out of the world anymore and are stuck in front of the "invisible wall".
![grafik](https://user-images.githubusercontent.com/17579552/120249140-28214600-c27a-11eb-81c5-8d25db959226.png)

**Comment by jhovgaard** [comment]
I wasn't able to reproduce. Still relevant?

**Comment by Gerwanese** [comment]
Just got it again:
![grafik](https://user-images.githubusercontent.com/17579552/121946185-f669ae00-cd54-11eb-8352-3a14b23e1047.png)

![grafik](https://user-images.githubusercontent.com/17579552/121946238-02557000-cd55-11eb-888f-fdf3d4d8be6f.png)

**Comment by jhovgaard** [comment]
Fixed in build 60
