### ISSUE TITLE
"Enter Building" doesn't work when standing too close in front of door

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#11]
When standing right in front of the door without any distance, the "Enter Building" button doesn't work. Clicking it doesn't do anything. It's not reproducible all the time but occasionally.
![grafik](https://user-images.githubusercontent.com/17579552/115997710-793b7b80-a5e4-11eb-866e-63d5e6dba109.png)

**Comment by jhovgaard** [comment]
Should be fixed by new UI.
