### ISSUE TITLE
Entering 21 Forthavenue not working correctly

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#110]
Build 49

21 Forthavenue is rented and I get the "click to enter" button, however the player just keeps running against the door.
After several seconds waiting time it will work and the player enters the building.

https://user-images.githubusercontent.com/17579552/120251553-34a99c80-c282-11eb-97c6-59a3f0639030.mp4

**Comment by jhovgaard** [comment]
Fixed in build 54
