### ISSUE TITLE
Placing serving desk in another building not working after already trying in first building

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#111]
Build 49

I first chose to place the serving desk in my small store but "grabbed" it again before placing.
Then I walked with the box to my large store and chose to place it there, however it doesn't show up. I can still "grab" it again and walk back to the small store where it shows up normally.
Both stores are just freshly rented with no business set up yet so there should be no different behaviour.

https://user-images.githubusercontent.com/17579552/120251814-feb8e800-c282-11eb-8572-33fc1fd68946.mp4

**Comment by jhovgaard** [comment]
Is this still relevant?

**Comment by Gerwanese** [comment]
Seems to be fixed already.
