### ISSUE TITLE
Ending up in void after leaving wholesale store

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#112]
Build 49

Went to the wholesale store (not drive-in but the normal store close to it).
Once leaving, I'm ending up in "void", unable to move at all.
![grafik](https://user-images.githubusercontent.com/17579552/120252174-104ebf80-c284-11eb-8b63-a96cfa6e4aa5.png)

When opening the map, this is where I seem to be (however, I also can't move the map anymore):
![grafik](https://user-images.githubusercontent.com/17579552/120252203-278dad00-c284-11eb-9f89-350b6b03dfa7.png)

**Comment by jhovgaard** [comment]
Fixed in some build
