### ISSUE TITLE
Not owned fast food restaurant: Can't buy anything but can pick salad/drink boxes

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#114]
In fast food restaurant stores which are not mine, I can't buy any meal. I can however walk behind the counter and pick salad and/or drink boxes.
I can't pay for those boxes and also can't leave with them so I just have to discard them.

In other shops it works different. For example in clothes store I can pick clothes and pay for them (although it's also a bit weird that I get a large box).

https://user-images.githubusercontent.com/17579552/120252904-39704f80-c286-11eb-9381-7748b88f7347.mp4

**Comment by jhovgaard** [comment]
Fixed in some build.
