### ISSUE TITLE
Cars disappear when entering 2nd Street besides Drive-In Wholesale store

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#115]
Build 49

When cars drive into the part of 2nd Street besides the drive-in wholesale store, they immediately disappear.
For my own car however the street is perfectly usable.

https://user-images.githubusercontent.com/17579552/120253448-a506ec80-c287-11eb-8893-599f860c9595.mp4

**Comment by jhovgaard** [comment]
This is by design on all roads leading to unfinished areas. I'll remove these despawners as the areas complete.
