### ISSUE TITLE
Can access other car's cargo while driving

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#117]
Build 49

While driving a car I can access my other car's cargo if I'm near enough.
The window will stay open even when driving away and I can discard any item.
Additionally, if clicking an item (not the red X but the item itself), afterwards I can't discard it for a moment (clicking on X doesn't work). After a while it worked again and I could discard all.

https://user-images.githubusercontent.com/17579552/120253917-f2378e00-c288-11eb-811d-417d9f845ec2.mp4

**Comment by jhovgaard** [comment]
Fixed in build 50
