### ISSUE TITLE
Sporadic Voogle Map glitches

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#119]
Build 49

Sporadically there are glitches in Voogle Maps. They occured several times but I didn't find any way to reproduce:

1. Map not draggable

https://user-images.githubusercontent.com/17579552/120372403-720c3980-c317-11eb-8718-3ca82865c9f4.mp4

The map seems to open up around the location where I got stuck in #112, so they might somehow be related?
Also notice that after first closing and reopening the map, it showed up  at the correct location but still not draggable. After slightly moving the car and reopening again, it's back to normal.
At other times, the map immediately opened at the right location the first time but was still stuck. Only seemed to happen while I'm in a car and not moving.

2. Sometimes the own businesses can not be selected on Voogle Maps and thus not be set as destination. Happend 3-4 times already to me but I never managed to catch it in video. It seems to happen with cars parked in front/nearby but even then I can't find a sure way to reproduce it.

**Comment by Gerwanese** [comment]
Build 55:
Similar to what is described in 1., I got the wrong location again when opening the map, but a different location this time (also far outside the building area, but to the north).

**Comment by Gerwanese** [comment]
Build 185:
Found a way to reproduce the wrong location issue.
When you leave a building, press M before the outdoor scene is loaded. That will open the map at the infamous "center" location.


https://user-images.githubusercontent.com/17579552/132094998-8f510043-6623-4ccf-9dc1-20b6892f8794.mp4

**Comment by jokoho48** [comment]
Fixed in Build 192.
