### ISSUE TITLE
Data of first business still filled in when starting second business

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#122]
Build 49

When starting two businesses right after each other, the second one will still have the data of the first one filled in.
After entering and exiting any building this is reset, starting business will start empty fields again.

https://user-images.githubusercontent.com/17579552/120374598-0b3c4f80-c31a-11eb-80e5-b4d08d6cda0c.mp4

**Comment by jhovgaard** [comment]
Fixed in build 55

**Comment by Gerwanese** [comment]
Only fixed for the name, but business type is still prefilled.

**Comment by jhovgaard** [comment]
Fixed in build 60
