### ISSUE TITLE
Juddery Shaddows

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#128]
Alpha 4 - Build 49

Shadows appear to judder across the screen when looking at an object closely,
https://i.adameg.net/4b5kEZ.jpg Also when they are moving gives a sort of jumping clockwise (For lack of better explanation) efffect. 
Not sure how much can be done, but thought best mention.

**Comment by Gerwanese** [comment]
Might be duplicate of #40 but I'll leave the decision to @jhovgaard

**Comment by jhovgaard** [comment]
They are the same yes :) Closing
