### ISSUE TITLE
Car driving on the sidewalk

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#13]
The silver car in the screenshot was driving down the sidewalk. It's not my car but a generated car.
![grafik](https://user-images.githubusercontent.com/17579552/115998173-55793500-a5e6-11eb-8d91-2fb6a8698453.png)

**Comment by Gerwanese** [comment]
Only happend once, never again. For now "can't reproduce".

**Comment by jhovgaard** [comment]
Bug in earlier version of STS. Fixed.
