### ISSUE TITLE
Seizure while sleeping

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#133]
Alpha 4 - Build 51

While sleeping your feet are shaking/ vibrating. 

Cant get a good video.

**Comment by Gerwanese** [comment]
Could not reproduce this, my legs were absolutely dead and sleeping. Will have to put cannot-reproduce for now.

**Comment by jhovgaard** [comment]
It might only be visible on higher resolutions, but I can see it.

It's the sleeping animation running at a higher speed to simulate fast-forward sleeping. I'll look into slowing it down a bit.

**Comment by jokoho48** [comment]
Fixed with new Timemachine Implementation.
