### ISSUE TITLE
Business "Gross Profit Margin" percentage display error

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#14]
In "Gross Profit Margin" the percentage shows "NaN" (Not a Number) for a newly started business.
After the first sales it will show infinite rise which is okay compared to previous day, however "infinite" is not shown in game language (probably using operating system language).
![grafik](https://user-images.githubusercontent.com/17579552/115998256-b3a61800-a5e6-11eb-9426-170088d026f6.png)
![grafik](https://user-images.githubusercontent.com/17579552/115998296-e8b26a80-a5e6-11eb-83bd-5de7bf2fbf45.png)

**Comment by jhovgaard** [comment]
Fixed in build 76
