### ISSUE TITLE
Large group of people spawn every time when leaving Metro Wholesale

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#146]
Build 51

Every time you leave the Metro Wholesale store, a bunch of people will spawn around you.

https://user-images.githubusercontent.com/17579552/120905502-b585e100-c652-11eb-90be-c418f257105f.mp4

**Comment by jhovgaard** [comment]
Caused by not all buildings been setup yet. Causes all pedestrians to spawn at the only and closest building.

**Comment by jhovgaard** [comment]
Fixed in build 79
