### ISSUE TITLE
Interviewee will stand still if I move away before starting interview

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#147]
Build 51

If I click on "Interview", the selected person will stand still. However if I walk away before reaching the person, the interview will not start and the person will be stuck.
If I come near that person later on, the interview will automatically start.
Expected behaviour would be that the interview is cancelled the moment I'm clicking somewhere else.

https://user-images.githubusercontent.com/17579552/120905686-1d88f700-c654-11eb-98ec-3f9773ee2a62.mp4

**Comment by jhovgaard** [comment]
Fixed in build 54
