### ISSUE TITLE
Queueing up with not enough money will leave me in queue 

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#149]
Build 51

If I queue up with not enouogh money for the item, a short red message will show up but I will still be kept in queue.
Instead I would expect to be removed from queue after the message about not enough money.

https://user-images.githubusercontent.com/17579552/120905943-d7349780-c655-11eb-8c6d-1ed51e00a2fd.mp4

**Comment by jokoho48** [comment]
Fixed in Build 191
