### ISSUE TITLE
Hand truck can be moved through wall

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#15]
The hand truck obviously still lacks a collision model and can be placed in the wall, making it hard to find (in case there's still some box on it, otherwise I could just get a new one).
![grafik](https://user-images.githubusercontent.com/17579552/115999015-58762480-a5ea-11eb-8870-cc06a1a7e585.png)

**Comment by jhovgaard** [comment]
Fixed in build 11
