### ISSUE TITLE
Right mouse button dragging to turn viewing angle will pick up items

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#154]
Build 54

When dragging with the right mouse button to turn the viewing angle, items will be picked up if the mouse is moved over them.
This can be pretty annoying inside shops.

https://user-images.githubusercontent.com/17579552/121816977-04e59600-cc7f-11eb-9bf1-a3d42cc8c15f.mp4

**Comment by jokoho48** [comment]
Fixed in Build 185
