### ISSUE TITLE
Shop type "FastFoodRestaurant" shows red outline in BizMan settings

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#159]
Build 55

Reason for the read outline is probably that FastFoodRestaurant is the first list entry - for a new shop, the first entry is the "please select" entry which has to be changed, so I guess the same rule applies hier although the "please select" entry is not in the list anymore.

![grafik](https://user-images.githubusercontent.com/17579552/121818203-0bc3d700-cc86-11eb-8d49-75d1345670c7.png)

**Comment by jhovgaard** [comment]
Fixed in build 75
