### ISSUE TITLE
Hand truck can move/lift vehicle

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#16]
The hand truck is able to lift and even roll over a large van.
![grafik](https://user-images.githubusercontent.com/17579552/115999080-a9861880-a5ea-11eb-8721-2ed7e8001385.png)

**Comment by jhovgaard** [comment]
Fixed in build 11

**Comment by Gerwanese** [comment]
Have to reopen this - I'm afraid you just fixed it for parked cars, not for those on the road...
Build 12

https://user-images.githubusercontent.com/17579552/116609883-31468c80-a935-11eb-9bc3-452f7406f9a4.mp4

**Comment by ChrisB-M** [comment]
Tested in build 12 this am and definitely still an issue

**Comment by jhovgaard** [comment]
Now fixed :)
