### ISSUE TITLE
"Residential" available as business type selection

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#160]
Build 55

In the business type combobox, it's possible to select "Residential". The description on the left side is then a mix, showing "Residential" but the description for a business.

![grafik](https://user-images.githubusercontent.com/17579552/121818251-49c0fb00-cc86-11eb-8c87-0498601f4c23.png)

**Comment by jhovgaard** [comment]
Fixed in build 75
