### ISSUE TITLE
Wrong location for picking up items in Appliance Store (just minor display issue)

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#161]
Build 55

Location for picking up items in Appliance Store:
- ❌ Industrial Fridge: Is picked up in front of the shop's Cash Register
- ❌ Standard Fridge: Picked up quite a bit in front of them
- ❌ Mop: Same location as Standard Fridge
- ❌ Cash Register: Picked up at the position for Mop
- ❌ Drings Fridge: Picked up from behind
- ❌ Shopping Baskets: Picked up from middle of store
- ✔️ Metal Shelf: Picked up from the "back side" but okay for me as they don't have a clear front and back
- ✔️ Clothing Rack: Correct position
- ❌ Serving Desk: Picked up from behind (from the "customer side"; might be correct, your decision)
- ❌ Small Industrial Freezer: Picked up from the worker side of the Serving Desk
- ✔️ Salad Bar: Correct position

https://user-images.githubusercontent.com/17579552/121818693-fd2aef00-cc88-11eb-8448-d1e76ba259b3.mp4

**Comment by jokoho48** [comment]
Fixed in the meanwhile.
