### ISSUE TITLE
Hand truck gets partially hidden on border of sidewalk

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#164]
Build 55

At the border of the sidewalk (between sidewalk and street) the hand truck gets partially invisible.

![grafik](https://user-images.githubusercontent.com/17579552/121819567-15e9d380-cc8e-11eb-8426-7603781e9919.png)

**Comment by jokoho48** [comment]
Fixed in the meanwhile(maybe even 190/191 due to the changes and offset of the Handtrucks and its new IK Animation)
