### ISSUE TITLE
1st Street: Marquee over sidewalk acts as wall

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#165]
Build 55

On 1st street, a marquee extending over the sidewalk acts as a wall, it's impossible to walk under it.
Additionally, I can't even walk in front of the building where there's no marquee.
AI people are able to walk there, only for myself it's impossible.
Also the building outline is triggered when moving the mouse over the inaccessible sidewalk area.

![grafik](https://user-images.githubusercontent.com/17579552/121820012-b04b1680-cc90-11eb-8791-b4d70c6dafa6.png)

https://user-images.githubusercontent.com/17579552/121820053-e5576900-cc90-11eb-82f5-a326267e0690.mp4

**Comment by Gerwanese** [comment]
Same problem for this building in the same street:
![grafik](https://user-images.githubusercontent.com/17579552/121820163-8f36f580-cc91-11eb-99b6-d62b7df52e0b.png)

**Comment by tomvbj** [comment]
same for this building also in the same streeet
![1Big Ambitions 6_13_2021 9_53_56 PM](https://user-images.githubusercontent.com/85610694/121820204-ea68e800-cc91-11eb-9baa-61596767066a.png)
![Big Ambitions 6_13_2021 9_55_47 PM](https://user-images.githubusercontent.com/85610694/121820228-08cee380-cc92-11eb-994a-c1dcd49b31fa.png)

**Comment by tomvbj** [comment]
Building next to the first building shown above has a wrong outline on Voogle maps.
![Big Ambitions 6_14_2021 7_55_35 PM](https://user-images.githubusercontent.com/85610694/121937123-a2f26280-cd4a-11eb-8099-f9268f72ac80.png)

**Comment by jhovgaard** [comment]
Fixed in build 131
