### ISSUE TITLE
Closing Voogle Maps unpauses game (but doesn't update UI)

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#166]
Build 55

When pausing the game and then opening and closing Voogle Maps, the game is automatically unpaused. The UI however still shows it as paused. Pressing Space once will update the UI and the game keeps running, so it's "repairing" itself.

https://user-images.githubusercontent.com/17579552/121820109-2c455e80-cc91-11eb-8f12-d2dad0f5ad49.mp4

**Comment by jhovgaard** [comment]
Fixed in build 75
