### ISSUE TITLE
Buildings not unhiding while game is paused

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#167]
Build 55

While the game is paused, buildings will auto-hide when necessary (when turning camera angle) but they will not unhide. After resuming the game, they will suddenly all show up again.

https://user-images.githubusercontent.com/17579552/121820593-11c0b480-cc94-11eb-812c-cff41c4f5063.mp4

**Comment by Albrat32** [comment]
Issue occurs if you pause game, go to Voogle maps and out again. Buildings are hidden at random
![Voogle1](https://user-images.githubusercontent.com/88228226/127733590-21db69ac-4964-4bc2-883f-edaa4d743338.png)

**Comment by jokoho48** [comment]
Fixed in build 180
