### ISSUE TITLE
Pathfinding: Character can get stuck between chairs and tables

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#17]
After being seated at a business (bank or recruitment agency both show the problem) sometimes the character is stuck and cannot move out of the triangle of the two chairs and desk. After some random clicking eventually the character is freed.
![grafik](https://user-images.githubusercontent.com/17579552/115999195-29ac7e00-a5eb-11eb-9f60-0c31f466e030.png)

**Comment by jhovgaard** [comment]
Fixed in some build
