### ISSUE TITLE
Car can after buying be placed in inaccessible position

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#176]
Build 55

After buying a car, it's possible that it's inaccessible due to parked vehicles right beside (most of the time it's still accessible even with parked vehicles though - probably here it happens because the parked vehicle is far to the right side in the parking lane).

https://user-images.githubusercontent.com/17579552/121822628-5ce0c480-cca0-11eb-962a-9d683b820b1c.mp4

**Comment by jhovgaard** [comment]
Fixed in build 67
