### ISSUE TITLE
Serving Desk can be placed against wall

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#189]
Build 55

The employee side of the serving desk can be placed right against the wall. The employee will then spawn on the other (customer) side and won't start to work.

![grafik](https://user-images.githubusercontent.com/17579552/121903071-39615c80-cd28-11eb-8e0d-ffcde1bf0f01.png)

**Comment by jhovgaard** [comment]
Fixed in build 76
