### ISSUE TITLE
Business schedule: Cannot assign separate employees to different shifts

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#19]
If my business has longer opening hours, several shifts will be automatically created. When trying to assign different employees however, the last selection is always set for all shifts.
For example if I select Jonas for shift 1, afterwards Hugo for shift 2, it will result in Hugo being set for both shifts.
![grafik](https://user-images.githubusercontent.com/17579552/115999453-12ba5b80-a5ec-11eb-8dac-bbd1fa6af88c.png)

**Comment by Gerwanese** [comment]
Additionally, when I unassign one shift (for example in the screenshot, I set 1. shift to "unassigned" but leave Thomas in 2. shift), the dialog will show the second shift still be assigned to the employee. If I close the dialog and open again, both shifts are now unassigned.

**Comment by jhovgaard** [comment]
Fixed in build 135
