### ISSUE TITLE
Car parked partly on road can flip and become inaccessible after entering&leaving building

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#190]
Build 55

If you park a vehicle partly on the road (just enough that cars can't pass) and then enter and leave a building, it will result in an accident ignoring physics.
Your own car can get flipped and depending on how it ends up, it can be inaccessible. In one case I needed to enter/exit a shop ~10 times until the car was in a position where I could enter it.
For demonstration purposes in the video, I parked it half way into the street but it doesn't need that much.

https://user-images.githubusercontent.com/17579552/121911150-c956d480-cd2f-11eb-99c1-72682bd8e49b.mp4

**Comment by jhovgaard** [comment]
Fixed in build 67
