### ISSUE TITLE
Closing BizMan with ESC in Voogle Maps also closes the map, closing by mouse click doesn't

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#196]
Build 55

If I open the BizMan of a business in Voogle Maps and close it with mouse click, I stay in Voogle Maps.
If I close it with ESC however, Voogle Maps will be closed as well.

https://user-images.githubusercontent.com/17579552/121951596-69762300-cd5b-11eb-9ebc-ac3cf71f4d8f.mp4

**Comment by jhovgaard** [comment]
Fixed in build 79
