### ISSUE TITLE
Path Finding: Character sometimes not walking to clicked on position

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#2]
Clicking in buildings doesn't always take the user to where they clicked.
(I know you already know, just thought would add here too)

**Comment by Gerwanese** [comment]
Example: In the recruitment agency, when clicking on the upper desk in the screenshot I will walk down and stop left of the chairs at the lower desk. When clicking on the lower desk in the screenshot I will walk towards the window.
![grafik](https://user-images.githubusercontent.com/17579552/115997997-886ef900-a5e5-11eb-9332-503b5a417129.png)

**Comment by jhovgaard** [comment]
Fixed by new mouse controller in earlier build.
