### ISSUE TITLE
Can Eat if hunger is already full

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#205]
Alpha 4 - Build 59

If you already have full hunger you can continue to eat, not sure if part of the future exercise mechanic, but seems like a bug.

**Comment by Gerwanese** [comment]
Not sure if it's a bug or just not implemented feature - that's from discord: > Yea the food burning mechanics isn't good yet

@jhovgaard Your decision :)

**Comment by jhovgaard** [comment]
Fixed in build 76
