### ISSUE TITLE
Objectives: "Assign the employee to the cash register" finished without employee

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#206]
Build 60

Probably should be viewed together with to #8 

The objective "Assign the employee to the cash register" was checked after I was working myself, without even having any employee yet.

https://user-images.githubusercontent.com/17579552/122455024-3eced900-cfac-11eb-8581-765e3d179076.mp4

**Comment by adameg2305** [comment]
Seems to be if you click the assign a colleague section and assign "unassigned" to the role, it counts it as an employee.

**Comment by jhovgaard** [comment]
Fixed in build 76
