### ISSUE TITLE
"Start working" in fast food restaurant not working

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#211]
Build 66

In a fast food restaurant it's not possible to work for myself. If I click "Start working", nothing happens (except for the dialog changing).
To close the dialog, I have to click "Stop working" twice, the first thing doesn't do anything at all.

https://user-images.githubusercontent.com/17579552/122656624-a75cb800-d15c-11eb-98ef-a073872bf59e.mp4

**Comment by jhovgaard** [comment]
Fixed in build 68
