### ISSUE TITLE
EconoView: Resources and sales items  - listed multiple times, wrong items

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#214]
Build 66

For gift shop the lines are shown twice, for fast food restaurant not.
For fast food restaurant, at first it showed only Salad and SodaCan. After one day, suddenly also Hotdog shows up (although not sold there).

![grafik](https://user-images.githubusercontent.com/17579552/122656547-d4f53180-d15b-11eb-92a2-f7860ae06268.png)

![grafik](https://user-images.githubusercontent.com/17579552/122657276-7f705300-d162-11eb-8ec6-d09df2c77dfa.png)

**Comment by jhovgaard** [comment]
Feeling confident this has been fixed.
