### ISSUE TITLE
BizMan: Dummy values shown for description and best selling products

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#216]
Build 66

In BizMan, Best Selling Products always shows Hot Dog for every business with the same item number and percentage.
Additionally, the description always shows the default description for empty business buildings which doesn't fit to FASTFOODRESTAURANT or GIFTSHOP.

![grafik](https://user-images.githubusercontent.com/17579552/122657474-2bff0480-d164-11eb-8c61-d97b14001aa2.png)

**Comment by jhovgaard** [comment]
Fixed in build 76
