### ISSUE TITLE
Cars put on sidewalk after purchase, multiple cars on top of each other

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#22]
When buying cars they're placed on the sidewalk with multiple cars on top of each other if I buy multiple.
![grafik](https://user-images.githubusercontent.com/17579552/115999880-033c1200-a5ee-11eb-8c9b-f58c8f42160c.png)
After driving the lower car (actually driving both on top of each other) and then parking the car, the top one will be ejected and end up in a troublesome position.
![grafik](https://user-images.githubusercontent.com/17579552/115999933-51511580-a5ee-11eb-9eeb-87e3dd515f8e.png)

**Comment by jhovgaard** [comment]
Added error message if previously purchase hasn't been picked up. Fixed in build 163
