### ISSUE TITLE
Supermarket: Possible to buy food during closed time if you have a job there

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#222]
Build 66

If you have a job at the supermarket, you can buy food at any time even if the shop is closed.
Also a cashier will always be there no matter the time.

https://user-images.githubusercontent.com/17579552/122798251-a8a6f580-d2c0-11eb-93b8-10fa293f69b6.mp4

**Comment by jhovgaard** [comment]
Fixed in build 75
