### ISSUE TITLE
Vehicles can push user

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#223]
Alpha 4 - Build 66

Vehicles can push the user without stopping, the vehicles also seem to move faster when a user is being pushed than normal.

**Comment by Gerwanese** [comment]
Confirmed, vehicles don't stop anymore at all.

**Comment by jhovgaard** [comment]
Fixed in build 68

**Comment by Gerwanese** [comment]
Not fixed at all in build 68 unfortunately. ;)


https://user-images.githubusercontent.com/17579552/123313430-d2168a00-d529-11eb-8978-76c52ff30caa.mp4

**Comment by jhovgaard** [comment]
Build number mess up again. Works in Build 70
