### ISSUE TITLE
Taking seat at Recruitment Agency while carrying hand truck will place hand truck on chair

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#224]
Build 66

If you carry a hand truck while taking seat at the recruitment agency, the hand truck will be placed on the chair (or rather "inside" the chair).
Once you finish the dialog, you'll suddenly move forward and now you're standing in the chair.

https://user-images.githubusercontent.com/17579552/122803034-6c769380-d2c6-11eb-9e82-a9a0e43ab782.mp4

**Comment by adameg2305** [comment]
Same for the bank as well

**Comment by jokoho48** [comment]
Fixed in Build 191.
