### ISSUE TITLE
Employees: Hourly wage is only charged once per day

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#225]
Build 66

The hourly wage of employees is only charged once per day according to BizMan (which is good  for now since otherwise it would be impossible to make money from the first gift shop...).

https://user-images.githubusercontent.com/17579552/122805370-4f8f8f80-d2c9-11eb-9629-308fe0af8606.mp4

**Comment by jhovgaard** [comment]
Fixed in build 70
