### ISSUE TITLE
"Punching" animation still there after finishing cashier job

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#226]
Build 66

After finishing my cashier job, the "punching" animation is still ongoing.
I think it's probably because I was handling a customer right at the time when my shift ended.

https://user-images.githubusercontent.com/17579552/122807023-5ae3ba80-d2cb-11eb-88aa-1ce12679510a.mp4

**Comment by Gerwanese** [comment]
Happened a second time with build 78 (new game, not saved from an old build).
Very rare but happening.

[Build78-PunchMe!.txt](https://github.com/hovgaardgames/bigambitions-public/files/6818413/Build78-PunchMe.txt)


https://user-images.githubusercontent.com/17579552/125679219-b78765c0-4205-4e55-96fe-d87ad1b35458.mp4

**Comment by jhovgaard** [comment]
Fixed in build 217
