### ISSUE TITLE
People not paying at supermarket

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#228]
Build 66

Thieves at the supermarket!
In the video you see three cases which are all pretty common:
First person takes shopping basket, food and pays for it.
Second person takes shopping basket food and then leaves without paying (shopping basket disappears).
Third person takes a look at the shopping basket and leaves.
Worst of all: They leave the door open!

https://user-images.githubusercontent.com/17579552/122808158-cb3f0b80-d2cc-11eb-93e7-8da7c7fd4225.mp4

**Comment by jhovgaard** [comment]
😂 They leave because of high prices or missing products. We'll have to do better explaining that tho.
