### ISSUE TITLE
Bank loan limit 1$ too low

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#229]
Build 66

The bank loan limit is actually 1$ lower than the banker says (maybe rounding issue?)

![grafik](https://user-images.githubusercontent.com/17579552/122810899-2b837c80-d2d0-11eb-8b3e-acc9e2647de7.png)

**Comment by jhovgaard** [comment]
@Gerwanese Can you send me the save for this? I'm having a hard time reproducing

**Comment by Gerwanese** [comment]
Had a hard time too but managed to get the savegame... limit is 38,685 but bank won't give me that.

[Build75-BankLoan.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773382/Build75-BankLoan.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124680784-6b995080-dec7-11eb-9822-900509e2246f.png)

**Comment by jhovgaard** [comment]
Fixed in build 76
