### ISSUE TITLE
Impossible to pick up boxes from store floor

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#23]
If boxes are placed on the floor inside a store, it's impossible to pick them up again. When clicking, the character will just walk around them.
![grafik](https://user-images.githubusercontent.com/17579552/116000160-52367700-a5ef-11eb-8b3f-219483d8f298.png)

**Comment by adameg2305** [comment]
You need to right-click them. then it will give you the option to move them or grab them, which you can then use to refill your shop

**Comment by Gerwanese** [comment]
Right, I wasn't able to do that before but now it worked. Case closed.
