### ISSUE TITLE
AutoRepairShop business available, but not VehicleLift

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#231]
Build 66

It is possible to open an "AutoRepairShop" business which requires a VehicleLift. There's no VehicleLift available in the game however.

![grafik](https://user-images.githubusercontent.com/17579552/122813505-53281400-d2d3-11eb-89d9-0f26f32cac69.png)

**Comment by Gerwanese** [comment]
As the repair shop is scheduled for a much later version, I guess it should be removed from the list. Especially while people in interviews still request it, so players will probably try to build it.

**Comment by jhovgaard** [comment]
Fixed by removing repair shop 😎 Build 75
