### ISSUE TITLE
Small Cabinet's movement border is too big.

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#232]
Alpha 4 - Build 67

In the starter flat if you go to move the small cabinet the cabinet has an extra square at the back of it so you cant place it against the wall anymore. 
![pm0THP](https://user-images.githubusercontent.com/44293115/123102226-be392e00-d42c-11eb-8a2d-3d7111a54fbe.png)

**Comment by jhovgaard** [comment]
Fixed in build 70
