### ISSUE TITLE
Objects placeable in room which cant be accessed.

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#233]
Alpha 4 - Build 67

In the first apartment you can place your bed in the closed off room, along with the fridge and small cabinet. You can still use the objects, and with the bed you can still sleep in the bed correctly, but you teleport into the room, and then out of the room at the end of the night.

![image](https://user-images.githubusercontent.com/44293115/123102716-415a8400-d42d-11eb-80d5-bed3ccfe7fe0.png)

**Comment by Gerwanese** [comment]
Fixed in the meantime, all rooms accessible.
