### ISSUE TITLE
Doors not opening uniformly 

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#236]
Alpha 4 - Build 67

The doors in the Metro Wholesale open in opposite ways. Should be same way to look uniform.

![FGwGsw](https://user-images.githubusercontent.com/44293115/123108842-ac5a8980-d432-11eb-9a74-dfbd7cc9d680.png)

**Comment by Gerwanese** [comment]
The same is true for Anderson Recruitment, Manhattan Business School, Appliance Store, City Cars. Probably for every two-door building. Might be intended but indeed it looks a bit weird. For me, it would be perfect if doors would always open "forward". If someone leaves the building, door will open to the outside. If someone enters, to the inside.

**Comment by jokoho48** [comment]
Fixed in Build 192.
