### ISSUE TITLE
Teleported outside of playable area. Stuck.

### ISSUE THREAD

**Issue by Cynikal3** [hovgaardgames/bigambitions-public#237]
![image](https://user-images.githubusercontent.com/2085032/123190541-b77edb00-d46d-11eb-866a-12481a863ea6.png)

I bought a van (red one), went to drive in wholesale.. loaded up, paid (was after hours when i finally paid)... drove up to the door, and it teleported me to the unplayable area. I am now blocked by invisible walls.

I'm on build A4-B67

**Comment by Gerwanese** [comment]
Confirmed. Happens every time when leaving the Drive-In Wholesales.

https://user-images.githubusercontent.com/17579552/123257881-04f15b80-d4f3-11eb-883c-7e2ae7ee08b8.mp4

**Comment by Cynikal3** [comment]
Is there a workaround to get the player back in normal play area? Or will I have to restart?

**Comment by Gerwanese** [comment]
Please save the game (new savegame name) in the stuck position. I'll try to create a fix for the savegame file.

**Comment by Gerwanese** [comment]
Try this: https://www.taiwantrip.info/bigambitions/repairlocation.php
You can upload your "broken" savegame, found here (the "AppData" folder is hidden, so either set Windows Explorer to show all files or type it manually):
`C:\Users\<username>\AppData\LocalLow\Hovgaard Games\Big Ambitions`
The resulting, repaired file has to go there as well. The savegame name will get "_fixloc" attached to the end of its name.

**Comment by Cynikal3** [comment]
Unfortunately, that did not work.
[Cynikal_SaveGameFiles.zip](https://github.com/hovgaardgames/bigambitions-public/files/6709526/Cynikal_SaveGameFiles.zip)

I added both the fix loc, and the original save game just incase you'd like to compare the two.

**Comment by Gerwanese** [comment]
@Cynikal3  Fixed your savegame:
[T1_fixloc.zip](https://github.com/hovgaardgames/bigambitions-public/files/6709917/T1_fixloc.zip)

Interestingly, although using the same location, the car ends up in different positions after loading. Anyways, as long as it's free again it should be fine.

**Comment by jhovgaard** [comment]
Fixed in build 68
