### ISSUE TITLE
Clicking on salad bar or drinks fridge in own store picks an unusable box

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#24]
When clicking on the salad bar or drinks fridge in my own store, I'll hold a box in hands. This box cannot put back but only be discarded or placed on the floor (the latter making it unusable).
![grafik](https://user-images.githubusercontent.com/17579552/116000217-9295f500-a5ef-11eb-82cb-14e4742ec6e2.png)

**Comment by jhovgaard** [comment]
Fixed in build 67
