### ISSUE TITLE
Item payment not registered if box in hands was saved

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#240]
Build 68

If you hold an unpaid box in hands and save the game, after reloading you can pay for it as many times as you want but it is never registered (the money is gone though).

https://user-images.githubusercontent.com/17579552/123315902-874a4180-d52c-11eb-8302-6da4476a8a64.mp4

**Comment by jhovgaard** [comment]
Fixed in build 70

**Comment by Gerwanese** [comment]
Build 70
Fixed by replacing with another bug: Now after reloading, I can queue up at the counter but nothing will ever happen.
Additionally, I start in front of the door with a stack of people "inside" the door who will not move at all.

Even worse: This does NOT change when discarding the box and picking a new one (still no reaction in queue) and even leaving the building, saving and reloading doesn't fix it. It effectively breaks the whole appliance store.

[BoxingDay.txt](https://github.com/hovgaardgames/bigambitions-public/files/6719165/BoxingDay.txt)


https://user-images.githubusercontent.com/17579552/123492737-a4f5d480-d61a-11eb-9fc2-fb787b38c22e.mp4

**Comment by Gerwanese** [comment]
Bug fixed in build 71.
