### ISSUE TITLE
Mouse drag registered as movement even when other dialogs/windows are opened

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#241]
Build 68

If you drag to select the prefilled text when saving a game, the player will start moving (nothing happens when clicking though).
You can also drag over the panels (for example phone app panel) and it will registered for movement.
If you drag inside a phone app (for example BizMan) and it is at a "valid" moving location, the player will start moving once you close the app.
This _might_ also be the issue in #173 - maybe in high speed the mouse is so sensitive that a click is registered as dragging?

I would say that dragging on the main screen over the overlays (objectives, phone, cargo) is good as it makes navigating much easier. It should be deactivated whenever another dialog / screen is open.

https://user-images.githubusercontent.com/17579552/123316816-92ea3800-d52d-11eb-97ab-059ddc959bb3.mp4

**Comment by jhovgaard** [comment]
Fixed in build 70

**Comment by Gerwanese** [comment]
Build 70: Fixed for the Save dialog but not within phone apps.

[Drag!.txt](https://github.com/hovgaardgames/bigambitions-public/files/6719138/Drag.txt)


https://user-images.githubusercontent.com/17579552/123492093-c35ad080-d618-11eb-95a0-880c490bc615.mp4

**Comment by Gerwanese** [comment]
Fixed in the meantime.
