### ISSUE TITLE
Saving while in the car will always let you start where you entered the car

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#242]
Build 68

If you save while you're in the car, after reloading you will always start at the position where you had entered the car, no matter how long before saving this was.
Only exception is the Drive-In Wholesales, entering and exiting the building are two more "saving points".

https://user-images.githubusercontent.com/17579552/123317728-a2b64c00-d52e-11eb-8f38-183d065765a4.mp4

**Comment by jhovgaard** [comment]
Fixed in build 70
