### ISSUE TITLE
Voogle Maps: Shop icons still shown when opening a phone app out of the map

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#245]
Build 69

If you open a phone app out of Voogle Maps, the icons for shops are still shown.

https://user-images.githubusercontent.com/17579552/123446498-3c3a3800-d5d9-11eb-8ebb-1e8d7bf67ae1.mp4

[NewStart-Build57.txt](https://github.com/hovgaardgames/bigambitions-public/files/6717167/NewStart-Build57.txt)

**Comment by jhovgaard** [comment]
Fixed in build 76
