### ISSUE TITLE
Icons and overlays "shaking" when dragging on Voogle Maps

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#246]
Build 70

When dragging Voogle Maps, the shop/car icons and also building overlays are "shaking". Glad I don't get seasick easily. ;)

[Voogle Maps.txt](https://github.com/hovgaardgames/bigambitions-public/files/6719120/Voogle.Maps.txt)

https://user-images.githubusercontent.com/17579552/123491667-8d691c80-d617-11eb-91ce-01c78ae8becf.mp4

**Comment by jokoho48** [comment]
Fixed in build 180
