### ISSUE TITLE
Voogle Maps: Shop/car icons are on top of building overlays

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#247]
Build 70

If I open a building overlay on Voogle Maps, existing shop/car icons are on top of it (unless you select the building with the icon itself, then it is hidden).

[Voogle Maps.txt](https://github.com/hovgaardgames/bigambitions-public/files/6719122/Voogle.Maps.txt)

![grafik](https://user-images.githubusercontent.com/17579552/123491773-d620d580-d617-11eb-99ac-cd354acde29c.png)

**Comment by jhovgaard** [comment]
Fixed at some point.
