### ISSUE TITLE
Dragging to select text in "Save" dialog while Voogle Maps is open will drag the map

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#248]
Build 70

Closely related to #241
If you open the Save dialog while Voogle Maps is open, selecting the text in the text field through dragging will move the map.

[Voogle Maps.txt](https://github.com/hovgaardgames/bigambitions-public/files/6719129/Voogle.Maps.txt)

https://user-images.githubusercontent.com/17579552/123491957-62cb9380-d618-11eb-81d3-bcb44a71b8c7.mp4

**Comment by jokoho48** [comment]
Fixed in Build 186
