### ISSUE TITLE
Entering the car with hand truck possible, but hand truck not usable after leaving car

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#25]
You can enter the car while carrying the hand truck. Once leaving the car you still hold it in hands, however it's not usable - picking up a box will place it in your hands instead of on the hand truck.
![grafik](https://user-images.githubusercontent.com/17579552/116000416-5fa03100-a5f0-11eb-8be0-3534dae2b6de.png)

**Comment by jhovgaard** [comment]
Fixed in build 10
