### ISSUE TITLE
Parking in drive-in wholesales is "illegal"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#252]
Build 71

Parking in the drive-in wholesales store is marked as illegal. This applies to your own vehicles as well as to the forklift.
It's not just a display issue, you even get fined for this.

[Build71.txt](https://github.com/hovgaardgames/bigambitions-public/files/6750664/Build71.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124186380-88471a00-dabc-11eb-9843-12300e564b6c.png)

![grafik](https://user-images.githubusercontent.com/17579552/124186864-36eb5a80-dabd-11eb-9984-f59d11460004.png)

![grafik](https://user-images.githubusercontent.com/17579552/124187826-ab72c900-dabe-11eb-9ac8-da2ca17efd7f.png)

**Comment by jhovgaard** [comment]
Fixed in build 75
