### ISSUE TITLE
Not paying any rent for fast food restaurant

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#258]
Build 71

For my fast food restaurant (10 Fourth Avenue) I'm not paying any rent at all according to the BizMan statement.

[Build71.txt](https://github.com/hovgaardgames/bigambitions-public/files/6750904/Build71.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124192038-f1cb2680-dac4-11eb-95f7-0e40c4240d3f.png)

**Comment by jhovgaard** [comment]
Fixed in build 75. Rent is set when clicking rent, so businesses have to be shut down and rented again to work.
