### ISSUE TITLE
Typo in street name of buildings in "FourthAvenue"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#259]
Build 71

All the buildings in 4th Avenue are labelled with "<NO> FORTHAVENUE", where the U of "FOURTH" is missing.

![grafik](https://user-images.githubusercontent.com/17579552/124192391-82a20200-dac5-11eb-83f8-4c59e3981dd1.png)

**Comment by jokoho48** [comment]
Fixed in the meanwhile.
