### ISSUE TITLE
Bank: No reaction when asking for extremely large amount

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#26]
When asking for a higher amount than allowed at the bank, you'll get a message telling you your personal limit.
If you enter an extemely high number however, nothing will happen at all when clicking the button.
![grafik](https://user-images.githubusercontent.com/17579552/116002084-4602e780-a5f8-11eb-95d9-12f5519c69e9.png)

**Comment by jhovgaard** [comment]
Fixed in Build 54
