### ISSUE TITLE
Can't enter car on double speed

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#261]
Build 73

When speed is set to double, it's not possible to enter a vehicle. The player will just run to different places next to the car but never enter it. Once speed is set to normal, it works immediately.
The driving cars in the video are not the issue, it always happens.

[Build71.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758753/Build71.txt)

https://user-images.githubusercontent.com/17579552/124361929-39bb8c00-dc32-11eb-88ba-111829e6b664.mp4

**Comment by adameg2305** [comment]
Not just Cars - Buildings are also hard to enter on 2x speed, but not impossible

**Comment by jokoho48** [comment]
double Speed was removed in Alpha 6 closing
