### ISSUE TITLE
Collection of shelf and box label issues in Drive-In Wholesales store

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#264]
Bulid 73

[Build71-Shopping.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758793/Build71-Shopping.txt)

Updated for the issues still there in build 76:

1. PaperBag: Picking a box will not show the number in the box but instead the "cargo" dialog which is usually used for a single paper bag. 
![grafik](https://user-images.githubusercontent.com/17579552/124362541-d2074000-dc35-11eb-817e-225386237146.png)
2. Shelves right of the Salad shelves: All three shelves show "PalletShelf" and nothing can be picked from them although they show boxes (this is probably because SaladBox had been here before).
![grafik](https://user-images.githubusercontent.com/17579552/124362630-670a3900-dc36-11eb-8573-39fddd0902d6.png)

**Comment by jokoho48** [comment]
Fixed in Build 192.
