### ISSUE TITLE
Box label shuddering when walking with it

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#265]
Build 73

When carrying a box and walking, the label is shuddering.

[Build71-Shopping.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758800/Build71-Shopping.txt)

https://user-images.githubusercontent.com/17579552/124362765-42fb2780-dc37-11eb-9b23-142e1c82d07d.mp4

**Comment by jhovgaard** [comment]
Looks like the game is throwing errors in the background. Is your FPS usually this low indoor?

**Comment by Gerwanese** [comment]
40-50fps is normal outdoors (can get down to around 30 sometimes) and in the drive-in store. In normal shops it's 60.

**Comment by jokoho48** [comment]
Fixed in the meanwhile (carried boxes don't have a ItemOverlay anymore)
