### ISSUE TITLE
Forklift not usable anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#266]
Build 73

The forklift will not pick up a pallet from the shelf anymore.

[Build71-Shopping.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758801/Build71-Shopping.txt)

https://user-images.githubusercontent.com/17579552/124362811-94a3b200-dc37-11eb-9d11-a194109e1080.mp4

**Comment by jhovgaard** [comment]
Seems to be fixed in build 74

**Comment by Gerwanese** [comment]
Bug is back in build 143.

[Build143-DontForkMyLift.txt](https://github.com/hovgaardgames/bigambitions-public/files/6946891/Build143-DontForkMyLift.txt)

**Comment by jhovgaard** [comment]
Fixed in build 145
