### ISSUE TITLE
Taking and returning items from container (DringsFridge, SaladBar...) will make them be lost

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#269]
Build 73

If you click on a container like DrinksFridge or SaladBar, you will pick up a box and the item count is reduced by 1.
If you click on the container again, the box will disappear but the item count will not go up again.

[Build71-FastFood.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758842/Build71-FastFood.txt)

https://user-images.githubusercontent.com/17579552/124363094-8a82b300-dc39-11eb-9c05-d739be13e43f.mp4

**Comment by jhovgaard** [comment]
Fixed in build 74

**Comment by Gerwanese** [comment]
Unfortunately not fixed in build 75.

[Build75-FridgeItemsLost.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773432/Build75-FridgeItemsLost.txt)

https://user-images.githubusercontent.com/17579552/124682061-32161480-deca-11eb-99b7-fab693884800.mp4

**Comment by jhovgaard** [comment]
Fixed in build 76
