### ISSUE TITLE
Store items sometimes not placeable

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#27]
Sometimes store items (in this case the counter, also happened with drinks fridge before) are not placeable.
Even when grabbing them again and retrying the problem still persists. Item will be stuck at a fixed location where you can only turn it by right clicking but not move it anywhere and it's never placed.
Only solution is to discard the item and buy again.

![grafik](https://user-images.githubusercontent.com/17579552/116002640-0093e980-a5fb-11eb-8d2c-f406aa68f535.png)

**Comment by jhovgaard** [comment]
Fixed in build 49.
