### ISSUE TITLE
SaladBox unusable and not possible to place anywhere

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#271]
Build 73

SaladBox is completely unusable: It can't be stored in salad bar or cash register and it also cannot be placed on the floor. Once bought, you can only discard it.

[Build71-Shopping.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758864/Build71-Shopping.txt)

https://user-images.githubusercontent.com/17579552/124363545-1c8bbb00-dc3c-11eb-9bd1-a2b622cc69c5.mp4

**Comment by jhovgaard** [comment]
Fixed in build 74
