### ISSUE TITLE
Can't pick up shopping basket in supermarket

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#274]
Build 73

Shopping baskets cannot be picked up at the supermarket anymore, effectively breaking the game as you can't eat.
Other customers will be stuck because of that as well. They will be displayed "leaned back" inside the wall - only when the game is paused, they will show normal again.

[Build73-Supermarket.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758885/Build73-Supermarket.txt)

https://user-images.githubusercontent.com/17579552/124363965-bce2df00-dc3e-11eb-97eb-c9b66a4405c6.mp4

**Comment by Gerwanese** [comment]
The problem only occurs in the "narrow" building types. If you're lucky and have a supermarket in one of the larger "square" buildings, the shopping basket works.

**Comment by jhovgaard** [comment]
Fixed in build 74
