### ISSUE TITLE
Fast Food Restaurant: Can't order food but only the appliances of the store

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#275]
Buidl 73

When queueing up at a fast food restaurant, I can't order food anymore. Instead I can "order" salad bar, drinks fridge and serving desk.

[Build73-Supermarket.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758901/Build73-Supermarket.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124364214-434bf080-dc40-11eb-80aa-fb12f36261ca.png)

**Comment by jhovgaard** [comment]
Fixed in build 74
