### ISSUE TITLE
Mop Holding animation

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#277]
Alpha 4 - Build 73

![image](https://user-images.githubusercontent.com/44293115/124364614-84d99d00-dc3a-11eb-9450-4ee67664299e.png)

Looks like you are holding a box

**Comment by Gerwanese** [comment]
Might be related to #278 because the mop is kind of treated like a box.

[Build71-FastFood.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758953/Build71-FastFood.txt)

**Comment by jokoho48** [comment]
Fixed in Build 190
