### ISSUE TITLE
Mop can be multiplied and turn into cardbox

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#278]
Alpha 4 - Build 73

Learn to dupe the mop!

Steps:
1) Have a mop in your business
![image](https://user-images.githubusercontent.com/44293115/124364594-72f7fa00-dc3a-11eb-9e0a-4d60a5a6b21f.png)
2) Pick up the mop, like you are going to use it to clean your floors
![image](https://user-images.githubusercontent.com/44293115/124364614-84d99d00-dc3a-11eb-9450-4ee67664299e.png)
3) Walk outside (While still holding mop)
![7BjyyI](https://user-images.githubusercontent.com/44293115/124364674-ea2d8e00-dc3a-11eb-9b0c-c98a51c6df80.png)
4) Mop will become a box
5) Go back inside
![UKwoV5](https://user-images.githubusercontent.com/44293115/124364688-0d583d80-dc3b-11eb-9c6b-746844e7be95.png)
6) Congrats an extra mop! (Until you walk outside again after placing the box)

**Comment by Gerwanese** [comment]
I think this is probably a compatibility issue in build 73.

Loading my savegame of build 71, returning the mop will not be possible and then grabbing again will give me a box.
Leaving and entering the building again, there's a new mop. If I now discard the box, save and reload, the new mop will work normally again.
Last word is up to Jonas but I would call it temporary. :)

[Build71-FastFood.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758942/Build71-FastFood.txt)

**Comment by jhovgaard** [comment]
@Gerwanese You're right. It was initially happening because players could exit while in cleaning mode. Has been fixed since :)
