### ISSUE TITLE
Can't leave shop with empty shopping basket (wrong message)

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#279]
Build 73

When trying to leave a shop with an empty shopping basket, I'll get the message that I have unpaid items in my basket which is wrong.
It should be either possible to leave with empty basket or the message should tell me to return the basket instead (I prefere the latter one).

[Build73-EmptyShoppingBasket.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758957/Build73-EmptyShoppingBasket.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124365204-c1ab9100-dc46-11eb-82d6-de27b721554b.png)

**Comment by jhovgaard** [comment]
Fixed in build 79
