### ISSUE TITLE
Price of first item put on hand truck after entering wholesales store will be shown double

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#280]
Build 73

After entering the wholesales store, if you do NOT pick the hand truck right away but instead first pick any box and then click on the hand truck, the item price will be shown double on the total amount.
At the cash register it's only shown once, so it's purely a display issue.
The same bug occurs at the appliance store, so it's a general hand truck bug.

[Build73_Wholesales_DoubleAmount.txt](https://github.com/hovgaardgames/bigambitions-public/files/6759054/Build73_Wholesales_DoubleAmount.txt)

https://user-images.githubusercontent.com/17579552/124367157-240b8e00-dc55-11eb-8abe-d1c1c456d539.mp4

**Comment by jhovgaard** [comment]
Fixed in build 77
