### ISSUE TITLE
Possible to "eat" Soda Can boxes

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#285]
Build 75

It's possible to "eat" boxes of soda cans.

[Build75-EatSodaCans.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773073/Build75-EatSodaCans.txt)

https://user-images.githubusercontent.com/17579552/124673601-6af9bd80-deb9-11eb-9e17-8a863b84c9fa.mp4

**Comment by jhovgaard** [comment]
Fixed in build 76
