### ISSUE TITLE
Objective "Stock up the cash register with paperbags" not registered

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#286]
Build 75

The objective "Stock up the cash register with paperbags" is not registered, although I have just done it.

In the savegame you're standing right in front of the store with all boxes. Just walk in, stock up cheap gifts and paperbags (the order does not matter, even when doing gifts first and paperbags afterwards, it's still not recognised).

[Build75-EatSodaCans.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773093/Build75-EatSodaCans.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124674056-4c47f680-deba-11eb-8920-7ca5d839cc8e.png)

**Comment by jhovgaard** [comment]
Fixed in build 76
