### ISSUE TITLE
BizMan shows wrong resources spend

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#288]
Build 75

The cost of resources in my gift shop is pretty wrong.
The day before yesterday (when I stocked up everything) shows higher cost than I even had money (15000 loan).
Yesterday even shows much more money spent.

[Build75-GiftShopEconoView.txt](https://github.com/hovgaardgames/bigambitions-public/files/6777144/Build75-GiftShopEconoView.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124676567-0e010600-debf-11eb-9e53-4e76e589c755.png)

**Comment by jhovgaard** [comment]
Fixed in build 76. Requires to buy new boxes and refill shelfs to force recalculation.
