### ISSUE TITLE
Own shop not registered as open when "Start working" dialog was opened before opening time

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#289]
Build 75

If you open the "start working" dialog in your own shop when it's still closed, the dialog will not register the opening time once it has passed, so you have to close and reopen the dialog to start working.

[Build75-GiftShopBeforeWork.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773218/Build75-GiftShopBeforeWork.txt)

https://user-images.githubusercontent.com/17579552/124677328-81574780-dec0-11eb-90fd-36889827b8f1.mp4

**Comment by jhovgaard** [comment]
Fixed in build 77
