### ISSUE TITLE
Selecting employee or "Unassigned" in BizMan schedule will break phone apps temporarily

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#291]
Build 75

Open BizMan, select "Schedule" open the combobox with only "unassigned" in it an click on that value. Alternatively, you can also go to "MyEmployees" first, assign the employee to the shop, then select him in the schedule - the bug will be the same (so it's not caused by the "unassigned" but by any selection in the schedule combobox).
Now the phone app is broken. While still in BizMan, you can only switch between the tabs "Insight" and "Inventory & Pricing". The other two don't react.
In the top navigation, "Messages", "EconoView" and "Interview Lite" don't react. Clicking on "MyEmployees" or "BizMan" will instead open the EconoView. In EconoView you can click on a shop name, but also there the "Open in BizMan" button doesn't work.
If you click on the very top right to close the dialog (not on "Close [ESC]" but even further right), apparently nothing happens. If you then close the dialog through "Esc" or click on "Close [ESC]", you will find that the click on the very right side opened the "Save" dialog in the background.

Once you close and reopen the phone app, everything works normal again.

[Build75-BizManUnassigned.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773354/Build75-BizManUnassigned.txt)

https://user-images.githubusercontent.com/17579552/124680344-7bfcfb80-dec6-11eb-84a0-df151dbea5e2.mp4

**Comment by jhovgaard** [comment]
https://user-images.githubusercontent.com/1388347/124928667-1745bc00-e000-11eb-96ea-43dfbce50803.mp4

Can't reproduce. Might be fixed by something else. Build 76

**Comment by Gerwanese** [comment]
I still got the same issue in build 76.
In your video you can select "Schedule" and "Settings" afterwards, that's not possible when I try it.
The other apps (MyEmployees, BizMan, EconoView) you only tried to open after closing the app before. After closing and reopening the issue is generally gone, so you would have to try it without closing in between.

**Comment by Gerwanese** [comment]
Magically fixed in build 78.
