### ISSUE TITLE
Cannot restock empty CheapGift shelf

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#292]
Build 75

When the metal shelf of CheapGift is empty, it's not possible to refill it anymore with a new box of CheapGift.

[Build75-CheapGiftRestock.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773414/Build75-CheapGiftRestock.txt)

https://user-images.githubusercontent.com/17579552/124681586-24ac5a80-dec9-11eb-9d6a-ab4a7d35d847.mp4

**Comment by jhovgaard** [comment]
Fixed in build 76
