### ISSUE TITLE
Message list not automatically updated when receiving a new message from already known sender

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#297]
Build 75

If you already have opened the messages from a sender (here: The City of New York), then close the messages app, get a new message from the same sender and open the app again, the message list initially isn't updated but only showing the previous message. Only after clicking the sender on the left side, the message list will be updated.

[Build75-DoubleParkingTicket.txt](https://github.com/hovgaardgames/bigambitions-public/files/6778467/Build75-DoubleParkingTicket.txt)

Uploading Big Ambitions_2021.07.07-17.33.mp4…

**Comment by jhovgaard** [comment]
Fixed in build 80
