### ISSUE TITLE
No reaction when training without enough money

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#299]
Build 75

If I select to train an employee but have not enough money, there's no reaction. Training will not be started but I also don't get any information about why.

[Build75-TrainNoMoney.txt](https://github.com/hovgaardgames/bigambitions-public/files/6778833/Build75-TrainNoMoney.txt)

https://user-images.githubusercontent.com/17579552/124797692-d774cb00-df52-11eb-95e7-5cee166aa47c.mp4

**Comment by jhovgaard** [comment]
Fixed in build 77
