### ISSUE TITLE
Traffic jams causing blocked roads

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#3]
Enough Said,

Traffic tends to crash into each other blocking all the roads, happens without any user interferance

**Comment by jhovgaard** [comment]
I've pushed build 5 which improves traffic a lot.

There might still be issues. Let me know if we need to reopen.

**Comment by Gerwanese** [comment]
I would think it needs some more work, still big trouble with deadlocks in Build 12.
One problem seems to be that cars sometimes just stop at the pedestrian crossing when turning and stay in that position forever even without any person walking there (second screenshot)
Another problem seems to be that cars always go with green light no matter whether they can cross the road or not. My recommendation would be to make sure that cars only drive if traffic light is green AND there's still free space in the lane they want to go into (straight ahead, left or right) to ensure they don't block the road crossing itself.

![grafik](https://user-images.githubusercontent.com/17579552/116483481-72806300-a887-11eb-9ae2-054b61143dd8.png)

![grafik](https://user-images.githubusercontent.com/17579552/116483757-fe928a80-a887-11eb-92d7-d3db745c8aef.png)

![grafik](https://user-images.githubusercontent.com/17579552/116483863-38fc2780-a888-11eb-88e3-7eb4ca4e0888.png)

**Comment by jhovgaard** [comment]
Should be much better now in build 54.
