### ISSUE TITLE
More dirt and (probably) longer lines when working on high speed

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#300]
Build 75

When working on high speed, customers leave much more dirt in the restaurant.
I also had the feeling that there are way longer lines when working in high speed compared to normal speed. I couldn't figure out however if it's because more customers are coming or handling of each customer is slower in high speed (I guess it's the handling time).

[Build75-NewRestaurant.txt](https://github.com/hovgaardgames/bigambitions-public/files/6778846/Build75-NewRestaurant.txt)

https://user-images.githubusercontent.com/17579552/124798153-57029a00-df53-11eb-8583-b8b16755ffec.mp4

**Comment by jhovgaard** [comment]
Switched to "unified dirt simulation". Fixed in build 79.
