### ISSUE TITLE
All prices in wholesales store (normal one and drive-in) are single prices instead of for a box

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#304]
Build 76

All boxes in the wholesales store and the drive-in wholesales only cost the price of a single item, although you still get a full box.

[Build76-EverythingOnDiscount!.txt](https://github.com/hovgaardgames/bigambitions-public/files/6795759/Build76-EverythingOnDiscount.txt)

https://user-images.githubusercontent.com/17579552/125172990-fa0a1c80-e1bc-11eb-9b2c-17da85ce185b.mp4

**Comment by Gerwanese** [comment]
Fixed in build 78

**Comment by Gerwanese** [comment]
Have to reopen - not completely fixed in drive-in wholesales.
Prices in the shelves are shown correctly, at the cash register you also have to pay the correct amount. In your car cargo however, the prices are all just for single items.

[Build78-LoadMyCargo.txt](https://github.com/hovgaardgames/bigambitions-public/files/6825531/Build78-LoadMyCargo.txt)

Uploading Big Ambitions_2021.07.15-20.39.mp4…

**Comment by jhovgaard** [comment]
Fixed in build 79
