### ISSUE TITLE
Possible to get stuck during interview

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#305]
Build 76

It is possible to get stuck during an interview, as you can see at the very end of the video.
It was probably caused by the interviewed person being pushed away from other pedestrians.

No savegame as it was a brand new game, after save/reload you're free and all pedestrians are gone.

https://user-images.githubusercontent.com/17579552/125173337-160ebd80-e1bf-11eb-9620-a5a2d87a456a.mp4

**Comment by jhovgaard** [comment]
Fixed by removing NPC colliders.

Build 80.
