### ISSUE TITLE
Employee staying at work one hour too long

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#306]
Build 76

While I appreciate employees staying after closing time if there's still a customer, staying for one hour overtime without a single customer might be a bit too much...

[Build76-EmployeeOvertime.txt](https://github.com/hovgaardgames/bigambitions-public/files/6795812/Build76-EmployeeOvertime.txt)

https://user-images.githubusercontent.com/17579552/125174180-cd0d3800-e1c3-11eb-9b9b-64bc10d63e8a.mp4

**Comment by jhovgaard** [comment]
Fixed in build 228
