### ISSUE TITLE
Traffic stopping too early

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#307]
Alpha 4 - Build 78

Cars are stopping well before the line when the lights are red or amber for them
![image](https://user-images.githubusercontent.com/44293115/125524639-8c34caba-b13c-48c1-95c4-a555377f28ca.png)

![image](https://user-images.githubusercontent.com/44293115/125524552-05b2bba6-03dd-4346-97a1-43dbec019805.png)

**Comment by Gerwanese** [comment]
Closing for now, as it happens by purpose.
