### ISSUE TITLE
Too Many notifications lead to offset text

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#309]
Alpha 4 - Build 78

When you get too many alerts on the right side of your screen the text no longer is in the middle of the notification bubble.
![9JlvKG](https://user-images.githubusercontent.com/44293115/125526158-526d38bf-d7fb-4f9d-a61e-47a770c9d031.png)

**Comment by Gerwanese** [comment]
[Build78-Stuffed.txt](https://github.com/hovgaardgames/bigambitions-public/files/6812103/Build78-Stuffed.txt)

https://user-images.githubusercontent.com/17579552/125527914-bc9356b8-3873-40f6-8dfe-596444051f13.mp4

**Comment by jhovgaard** [comment]
Fixed in build 80
