### ISSUE TITLE
"Start working" button visible behind "stop working" button

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#311]
Build 78

If you start work and switch to high speed, a part of the blue "start working" button becomes visible.

[Build75-GiftshopNoCustomers.txt](https://github.com/hovgaardgames/bigambitions-public/files/6812163/Build75-GiftshopNoCustomers.txt)

https://user-images.githubusercontent.com/17579552/125529056-39652bc4-7bfd-4f1b-8a74-5d3af3a6d742.mp4

**Comment by jhovgaard** [comment]
Fixed in build 80
