### ISSUE TITLE
Opening and closing Voogle Maps quickly multiple times will pause the game

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#313]
Bulid 78

Usually when opening Voogle Maps the game will get paused, and when closing it the game will go to the previous state (paused or running, depending on how it was before opening the app).
If you quickly open Voogle Maps at least twice however, the game will be paused afterwards even if it was running before first opening the app.
This works with shortcut M as well as by clicking the app icon.
Probable cause: I think the second time Voogle Maps is opened already before the first time closing it could unpause the game. So the second time opening it was done in a still paused state.

Any savegame or even new game will do.

https://user-images.githubusercontent.com/17579552/125530587-2ee2a9cd-84c3-48b0-b7b7-8661d0db0fe6.mp4

**Comment by jokoho48** [comment]
Fixed in build 180
