### ISSUE TITLE
InterviewLite: Lower half of district tabs don't react on mouse click

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#314]
Build 78

When switching between the four districts in the InterviewLite app, the lower half (or maybe lower 40%) of the texts is not clickable. Only if you click in the upper part of the text (or even a bit above it), the click will be registered and the district selected.

Any savegame or a new game will do.

https://user-images.githubusercontent.com/17579552/125531229-cb6e3a11-baff-4e23-ac7d-d7c7f87e16eb.mp4

**Comment by jhovgaard** [comment]
Fixed in build 79
