### ISSUE TITLE
Working with a paper bag in hands will make the bag disappear

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#317]
Build 78

If you start working with a paper bag in hands (even if it has contents), the paper bag will be gone after finishing work.

[Build78-DontWorkAndDrink.txt](https://github.com/hovgaardgames/bigambitions-public/files/6818665/Build78-DontWorkAndDrink.txt)

https://user-images.githubusercontent.com/17579552/125685663-c0844d68-557e-4502-86bc-69917af431e5.mp4

**Comment by jokoho48** [comment]
Fixed in the meanwhile.

**Comment by jokoho48** [comment]
Reopening this issue as it still happens and the save game is just broken.

**Comment by jhovgaard** [comment]
Fixed in build 194
