### ISSUE TITLE
Customers can get stuck when surrounded by others

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#318]
Build 78

Customers in a shop can get stuck if too many of them come in and the "first" one at the shelf gets surrounded so he can't leave the shelf anymore.
Happened in fast forward.

[Build78-DontWorkAndDrink.txt](https://github.com/hovgaardgames/bigambitions-public/files/6818706/Build78-DontWorkAndDrink.txt)

https://user-images.githubusercontent.com/17579552/125686946-0694c963-89a3-484b-b8b8-d211f43d3941.mp4

**Comment by Gerwanese** [comment]
Moving to alpha 5 as this also massively happens in normal speed.
Had to leave and re-enter the appliance store 3 times because every time people queued in front of me were stuck somewhere in the shop so I couldn't pay.

**Comment by jhovgaard** [comment]
Removed colliders for NPCs. Max'ed player avoidance priority.

Fixed in build 80.

**Comment by Gerwanese** [comment]
People are still pushing each other. See bug #335, but also inside the shop. You can see one person at the counter being pushed away after paying and now being able to leave the shop; more customers later in the video are all around the shelf.

Same savegame as in the initial report of this bug.

https://user-images.githubusercontent.com/17579552/126510956-0f53fb58-055e-4792-8c42-c49f4cf8b890.mp4

**Comment by jhovgaard** [comment]
Temporary fixed in build 89.
