### ISSUE TITLE
Employee paid base wage on top of hourly wage

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#319]
Build 78

When employees are unassigned, they get paid a daily wage of 60$ which I think is okay (they're employed by you, so you have to pay).
When they're working for the current default wage of 15$ however, they get paid the 15$/hour plus the 60$ default wage which on a 8 hour shift is an increase of 50%.

In my game it's a 10 hour shift:

[Build78-WageRage.txt](https://github.com/hovgaardgames/bigambitions-public/files/6818763/Build78-WageRage.txt)

![grafik](https://user-images.githubusercontent.com/17579552/125688376-8eece40d-d718-4905-b1f6-d5c617d1427e.png)

**Comment by jhovgaard** [comment]
Fixed in build 79
