### ISSUE TITLE
Pathfinding: Player runs onto street instead of straight on the sidewalk if the target is near road

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#320]
Build 78

This issue came up a few builds ago already and now I could savely reproduce it:

If you let the player run straight on the sidewalk, but the target is near the edge towards the road, sometimes the player suddenly makes a move onto the street in front of parked cars.
This happens more frequently when dragging, obviously because the "permanent click" gives more chances for the bug to show up, but also when just clicking it happens.

It might be caused by cars slightly parked on the sidewalk; however, even if they are in the way, avoiding to the other side (to the "house" side of the sidewalk) would be the much shorter way.

In the video, the first two times I use dragging - both times the player runs onto the street in front of the red van.
The other two times I use clicking. The first time the player just runs normally (maybe it was too far towards the middle of the sidewalk). The second time he runs onto the street even earlier, in front of the white van, and then has trouble getting back onto the sidewalk because he first tries to rob the star from the black Merc.

[Build78-StreetWalker.txt](https://github.com/hovgaardgames/bigambitions-public/files/6818928/Build78-StreetWalker.txt)

https://user-images.githubusercontent.com/17579552/125692548-4be81eca-257c-45c8-ab94-df871a9f0af3.mp4

**Comment by jhovgaard** [comment]
Fixed in build 80.
