### ISSUE TITLE
Employee candidate message empty

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#322]
Build 78

I requested to get 10 candidates within one day.

Three messages I already deleted, two are still in my inbox - but one of them is empty and doesn't show any employee.

[Build78-Emptyployee.txt](https://github.com/hovgaardgames/bigambitions-public/files/6819154/Build78-Emptyployee.txt)

![grafik](https://user-images.githubusercontent.com/17579552/125698766-c1a1bef4-693a-4e92-99f5-ac8b5bed2cde.png)

**Comment by jhovgaard** [comment]
Fixed in build 80
