### ISSUE TITLE
Price balancing issues

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#323]
Build 78

Prices per unit at Metro Wholesales vs. standard sales prices:
Item                     | Price Per Unit              | Price Per Unit Drive-In | Standard Sales Price              | Maximum accepted price before you get complaints
-------------------|-----------------------|-------------------------------|--------------------------------|---------------------
PaperBag              | $1.10 ($1100 / 1000) | $0.90 ($900 / 1000) | $1                                         |
CheapGift             | $11 ($2200 / 200)      | $9 ($1800 / 200)      | $10 (gift shop)                       | $12
SodaCan               | $4.40 ($264 / 60)       | $3.60 ($216 / 60)     | $4                                         | $4.70
Salad                     | $8.80 ($3080 / 350)   | $7.20 ($2520 / 350) | $8                                         |
HotDog                 | $8.80 ($880 / 100)     | n/a                           |                                              |
FreshFood             | $11 ($550 / 50)          | $9 ($450 / 50)          | $10                                       | $12
FrozenFood           | $110 ($5500 / 50)      | $90 ($4500 / 50)      | $100                                     | $120
NonFood               | $110 ($5500 / 50)       | $90 ($4500 / 50)     |                                              |
ClassicCheapMaleClothing | $22 ($1100 / 50) | $18 ($900 / 50)   | $20                                       | $24
ClassicCheapFemaleClothing   | n/a                 | $18 ($900 / 50)   | $20                                       | $24
ModernCheapMaleClothing    | n/a                 | $27 ($1350 / 50) | $20                                       | $36
ModernCheapFemaleClothing | n/a                 | $27 ($1350 / 50) | $20                                       | $36

This is all data I collected. HotDog and NonFood don't have a "container" for selling yet so I can't see the default prices. I didn't check out the customer acceptance for all items yet.
Usually real world margin would be at least 30-50% (realistically it often is around 100% for retail). The default setting should at least be 10% over the purchase price (better 20%) to avoid people running into trouble all the time.

- FreshFood costs $11 at the supermarket (same like metro wholesales) and will fill your stomach about 60-70% (rough guess). At the pizza place I get Salad for $8 and SodaCan for $4 with Salad filling me about the same like FreshFood. Shouldn't supermarket be cheaper than a restaurant?

[Build78-Emptyployee.txt](https://github.com/hovgaardgames/bigambitions-public/files/6819166/Build78-Emptyployee.txt)

**Comment by jhovgaard** [comment]
Fixed in build 79
