### ISSUE TITLE
Car dealer: Car spawning position still at the old, previous location

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#327]
Build 78

If you make it to the car dealer through... hidden ways... the purchased car will still spawn at the previous location.
Also the orange pylons are still at the old location of the shop.

[Build78-Cheat3.txt](https://github.com/hovgaardgames/bigambitions-public/files/6825241/Build78-Cheat3.txt)

![grafik](https://user-images.githubusercontent.com/17579552/125833328-a9f8d28f-fbc5-413a-a175-4f59b6461766.png)

**Comment by jhovgaard** [comment]
Fixed in build 131 by hiding old buildings/dealer
