### ISSUE TITLE
Paper bags are not paid for

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#329]
Bukd 78

I have set my paper bag price to $1000.50 and wondered why no customer complains about the price and they all get a paper bag. The reason is simple: They don't pay for it.
With 29 sold items in my 24h Hypermarket (and thus 29 sold paper bags), there would have been a significant income from the paper bags, however there's just a minus at the end of the day (not just in EconoView, where the paper bag doesn't show up, but also on my bank account which I checked).

If paper bags are expected to be free, there shouldn't be the option to set a price for them. If they're not expected to be free, it would be nice to actually get the money. :)

[Build78-PriceyPaperBags.txt](https://github.com/hovgaardgames/bigambitions-public/files/6825769/Build78-PriceyPaperBags.txt)

**Comment by jhovgaard** [comment]
Fixed in build 79.
