### ISSUE TITLE
Picking up box and then using Handtruck causes both held separately

### ISSUE THREAD

**Issue by ChrisB-M** [hovgaardgames/bigambitions-public#33]
Picking up box (in this case a mop) and then using the handtruck causes issue where you are carrying a box and driving an empty Handtruck

One other strange thing is that the mop box is much bigger than it usually is (guessing the size of the handtruck box)

![mop handtruck](https://user-images.githubusercontent.com/6843892/116092267-8ff1d900-a69d-11eb-9322-64b64f3fcd69.PNG)

**Comment by jhovgaard** [comment]
Fixed in build 10
