### ISSUE TITLE
Time Machine will unpause game after finishing work, but not update UI

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#330]
Build 82

After finishing work, the time machine will unpause the game if it was paused before. The UI still shows it paused however.

[Build75-GiftshopNoCustomers.txt](https://github.com/hovgaardgames/bigambitions-public/files/6854442/Build75-GiftshopNoCustomers.txt)

https://user-images.githubusercontent.com/17579552/126466250-a0a7cbd0-5da5-42f1-9d50-4178239a4c93.mp4

**Comment by jhovgaard** [comment]
Fixed in build 83
