### ISSUE TITLE
Time machine advancing time too far

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#331]
Build 83

Time machine is overspeeding: My shift ends at 20:00, time machine however will boost me to 23:00.

[Build75-GiftshopNoCustomers.txt](https://github.com/hovgaardgames/bigambitions-public/files/6854702/Build75-GiftshopNoCustomers.txt)

https://user-images.githubusercontent.com/17579552/126471820-c26fecf7-f88f-4c17-a15b-4fd8d5ee7bce.mp4

**Comment by jhovgaard** [comment]
Fixed in build 84
