### ISSUE TITLE
Gift shop (not self-owned): No label for items on shelf; gift price is $0 and not payable

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#336]
Build 85

In the gift shop the shelves don't display what items are on them.
Furthermore, if you pick an item it is shown as $0 in your basket. You can't pay it but you also can't leave the store with it.

[Build78-FreeGiftsForEveryone.txt](https://github.com/hovgaardgames/bigambitions-public/files/6856229/Build78-FreeGiftsForEveryone.txt)

https://user-images.githubusercontent.com/17579552/126499963-1b9b7a69-055e-4dde-8331-5f239f67cc46.mp4

**Comment by jhovgaard** [comment]
Fixed in build 131
