### ISSUE TITLE
Several issues with district tabs in Interview Lite app

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#338]
Build 85

It seems the bugfix for #314 caused a few new issues:
- Interview Lite app always opens Midtown as default instead of Garment District
- When loading an old savegame (the attached one) and opening Interview Lite for the first time, Midtown is shown in white but not underlined in white (selection underline completely missing)
- When closing and opening Interview Lite again, now the initial white underline is there but it's in the middle between MurrayHill and Midtown
- When starting a new game and opening Interview Lite, all the tab titles are moved down so the grey line goes right through the texts
- In the new game when opening the app for the first time, the white underline is missing too. For every consecutive opening of the app, it's shown at the right place however.

[Build78-WeWantYOUForHypermarket!.txt](https://github.com/hovgaardgames/bigambitions-public/files/6856357/Build78-WeWantYOUForHypermarket.txt)

https://user-images.githubusercontent.com/17579552/126502982-307ef854-b1d7-4528-99b0-4cb040910e58.mp4

**Comment by jhovgaard** [comment]
Fixed in build 89
