### ISSUE TITLE
Drive-in wholesales: Fence green from inside parking lot

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#340]
Alpha 4 - Build 85

The fence down at the new Wholesale drive-in store, the fence on the side of the road is see-through looking into the road, but is green when looking out onto the road. 

https://user-images.githubusercontent.com/44293115/126503996-50c64721-f588-4e80-8f6f-6d09efb63be7.mp4

**Comment by Gerwanese** [comment]
[Build78-ParkNotPeek.txt](https://github.com/hovgaardgames/bigambitions-public/files/6856508/Build78-ParkNotPeek.txt)

**Comment by Gerwanese** [comment]
Fixed in build 106
