### ISSUE TITLE
Stocking up shelf leaves the box in your hand.

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#341]
Alpha 4 - Build 85
When you go to stock up a shelf and click on the shelf it gets filled up with the item but the box still remains in the hand of the user. 
The Dev console gets spammed with "NullReferenceExceptions"
https://user-images.githubusercontent.com/44293115/126505076-63f737d1-f79d-484f-b3ea-8e473d3a04f0.mp4

[Player Log.txt](https://github.com/hovgaardgames/bigambitions-public/files/6856507/Player.Log.txt)

**Comment by Gerwanese** [comment]
[Build78-BadBoxes.txt](https://github.com/hovgaardgames/bigambitions-public/files/6856605/Build78-BadBoxes.txt)

Confirmed, also drinks fridge and cash register (paper bags).

**Comment by jhovgaard** [comment]
Fixed in build 89
