### ISSUE TITLE
Parking on parking lot of drive-in wholesales is illegal

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#344]
Build 85

The parking lot of the drive-in wholesales store doesn't allow parking, all parking spots are "illegal".

[Build78-ParkNotPeek.txt](https://github.com/hovgaardgames/bigambitions-public/files/6856545/Build78-ParkNotPeek.txt)

![grafik](https://user-images.githubusercontent.com/17579552/126506315-fc2df6e1-7079-4448-b452-1b803a09fafd.png)

**Comment by jhovgaard** [comment]
Fixed in build 89
