### ISSUE TITLE
Tutorial still mentioning Hell's Kitchen instead of Garment District

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#348]
Build 85

The tutorial step for the citizen interviews still mentions Hell's Kitchen.

[Build78-MessageTLDR.txt](https://github.com/hovgaardgames/bigambitions-public/files/6857008/Build78-MessageTLDR.txt)

![grafik](https://user-images.githubusercontent.com/17579552/126517485-dad579db-7646-4d5a-b83b-afedb9e4fbb3.png)

**Comment by Gerwanese** [comment]
Added to Alpha 5 although not a serious issue, but with lots of new players coming up this might cause confusion.

**Comment by jhovgaard** [comment]
Fixed in build 89
