### ISSUE TITLE
Pathfinding for citizens - citizens can get stuck running at a lip in the wall

### ISSUE THREAD

**Issue by ChrisB-M** [hovgaardgames/bigambitions-public#35]
This makes them impossible to interact with, even if you "bump" them to get them back on track

![citizen pathfinding](https://user-images.githubusercontent.com/6843892/116095075-fbd54100-a69f-11eb-8532-ea0c4c4b99b4.PNG)

**Comment by Gerwanese** [comment]
I could verify that this happens at two locations:
1. The  recruitment agency (at the door)
2. The location shown in the screenshot in this bug report
At both locations people are alway stuck at any time, independent of shop opening times.

The locations on Voogle Maps:
![grafik](https://user-images.githubusercontent.com/17579552/116140615-debc6480-a6d7-11eb-8500-b2988ea902cc.png)

**Comment by jhovgaard** [comment]
Fixed in Build 9.
