### ISSUE TITLE
Run Behind Buildings

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#350]
Alpha 5 - Build 106

You can run through building 24th Third Street, it is no longer recognized as a building.

https://user-images.githubusercontent.com/44293115/127399166-fac72fd8-4156-4500-894e-16accc07d2b1.mp4

[106save.txt](https://github.com/hovgaardgames/bigambitions-public/files/6896569/106save.txt)

**Comment by Gerwanese** [comment]
Merged to #97 (same issue with the building, just got worse with not blocking anymore)
