### ISSUE TITLE
Side room in apartment can't be accessed anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#351]
Build 106

In the apartment, the closed room could never be accessed but the open side room (the one without door) was accessible perfectly.
Now it's not anymore.
Additionally you can still place the fridge in both side rooms but can't put anything into it anymore (before it was possible even without getting there).

See also related bug #233.

[Build106-FridgeIsClosedForYou.txt](https://github.com/hovgaardgames/bigambitions-public/files/6896594/Build106-FridgeIsClosedForYou.txt)

https://user-images.githubusercontent.com/17579552/127399181-ae536ecf-f4b2-4419-a52f-577ecb632c99.mp4

**Comment by jhovgaard** [comment]
Fixed in build 131. Or 132.
