### ISSUE TITLE
Grammar in bank loan screen

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#353]
Alpha 5 - Build 106

Should be "Borrow" instead of "loan"
![GSXp57](https://user-images.githubusercontent.com/44293115/127400726-d187b289-17aa-4d38-a1c7-915f68cf4866.png)

**Comment by Gerwanese** [comment]
Also in the "denied" message.

[Build106-BankersCantSpeakProperEnglish.txt](https://github.com/hovgaardgames/bigambitions-public/files/6896673/Build106-BankersCantSpeakProperEnglish.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127401416-3e14f7d4-28a7-474b-82cb-cc7357dd283a.png)

**Comment by jhovgaard** [comment]
Fixed in build 131
