### ISSUE TITLE
Can't buy gifts, paper bags and others from wholesales store

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#355]
Build 106

At the wholesales store, I can only by the items on shelves facing the center of the room. When picking those, the player will walk to the opposite side of the room and get the box there.
When clicking on the shelves facing the oudside/walls of the shop, nothing happens. Unfortunately this means I can't buy CheapGifts and Paperbags.

[Build106-TheyDontSellMeGifts.txt](https://github.com/hovgaardgames/bigambitions-public/files/6896718/Build106-TheyDontSellMeGifts.txt)

https://user-images.githubusercontent.com/17579552/127402635-657204fe-cd0a-4160-9d6f-9f0bc0a963a9.mp4

**Comment by jhovgaard** [comment]
Fixed in build 117
