### ISSUE TITLE
Player can get trapped in the drive-in wholesales

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#358]
Build 106

It's possible to walk "into" the drive-in wholesales store without actually entering it. You're then caught inside the walls of the building.
The only regular chance to get out is through the "Enter building" button but once the shop is closed that's not possible anymore. There's also a chance through double speed to get out sometimes but not reliable.

[Build106-DriveInOrWalkThrough.txt](https://github.com/hovgaardgames/bigambitions-public/files/6896845/Build106-DriveInOrWalkThrough.txt)

https://user-images.githubusercontent.com/17579552/127405947-0d586c2e-a7d8-4346-84d9-1f84f6739250.mp4

**Comment by jhovgaard** [comment]
Fixed in build 109
