### ISSUE TITLE
Vehicles change color when entering and leaving a building

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#36]
When entering the vehicle shop with an existing van and then leaving the shop the van has changed color.

**Comment by adameg2305** [comment]
Tested with other shops, it has the same effect of changing the vans colour

**Comment by adameg2305** [comment]
Not just vans it is also the cheap sedan which changes

**Comment by jhovgaard** [comment]
Fixed in build 10.
