### ISSUE TITLE
Many buildings have "Company Name" signboard

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#361]
Build 120

The building 18th Third Street shows a signboard "Company Name" although it's a residential building.
If I walk towards it, the signboard will disappear but opening and closing Voogle Maps will bring it back.

Other buildings with the same issue:
13 Fifth Avenue
1 Fifth Avenue
all Third Avenue buildings (last screenshot)
Many other buildings in all the other streets as well

[Build106-CompanyName.txt](https://github.com/hovgaardgames/bigambitions-public/files/6903527/Build106-CompanyName.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127563427-d9e12dac-4720-465f-a417-0cf6eeb34ce4.png)

![grafik](https://user-images.githubusercontent.com/17579552/127565221-c9ace6bf-2a18-46c4-8e65-9709f7626710.png)

**Comment by jhovgaard** [comment]
Fixed in build 131

**Comment by Gerwanese** [comment]
"Company Name" now is not shown initially on buildings anymore.
However, it's still there on your own buildings: Ff you rent a new commercial building and don't start a business, after closing the BizMan there will be no signboard at the building. If you enter and exit the building, the "Company Name" signboard will show up.

[Build132-RentRant.txt](https://github.com/hovgaardgames/bigambitions-public/files/6919494/Build132-RentRant.txt)

https://user-images.githubusercontent.com/17579552/127920870-5fe94054-a4d4-4f1c-82b3-133834dff178.mp4

**Comment by Gerwanese** [comment]
Additionally, the large building 3rd Avenue / 2nd Street / 3rd Street shows "Company Name" permanently.

![grafik](https://user-images.githubusercontent.com/17579552/128506240-adc4f9cb-12b2-4932-8b39-ffcc9d8fda51.png)

**Comment by jokoho48** [comment]
Fixed in the meanwhile.
