### ISSUE TITLE
Hidden road block at corner 3rd Avenue / 3rd Street

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#364]
Build 120

At the corner of 3rd Avenue and 3rd Street there's a hidden road block at the repaired part of the road (but not the repaired itself, you can drive over it).

[Build106-HiddenBlock.txt](https://github.com/hovgaardgames/bigambitions-public/files/6903598/Build106-HiddenBlock.txt)

https://user-images.githubusercontent.com/17579552/127565694-1a05a6ad-0f54-49a5-b55c-3a85f08aad5e.mp4

**Comment by adameg2305** [comment]
Also at 1st Street outside grey building (Not Yet Labelled) covers the entire front of the building

![image](https://user-images.githubusercontent.com/44293115/127566341-160083bd-e3e5-482f-820b-6784ee350974.png)

**Comment by Albrat32** [comment]
1st street. Any buildings on there with objects over the sidewalk.. Block the player from walking along the sidewalk. (can walk on road around it.)

**Comment by jhovgaard** [comment]
Fixed in build 131
