### ISSUE TITLE
Possible to accept multiple and unpaid supermarket jobs

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#366]
Build 120

It's possible to accept multiple supermarket jobs.
After taking the (unpaid) job at 10 Third Street, I still got the "Accept" button at any of the other supermarkets (as many as I want). The jobs get stacked on top of each other, always showing the first accepted on top. When I quit the job, the next one will show and so on.

The job will forever show as "Day off".

[Build106-MultiJobAccepted.txt](https://github.com/hovgaardgames/bigambitions-public/files/6903560/Build106-MultiJobAccepted.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127564226-59b8cdf2-f5d4-45d7-8356-0997649008a9.png)

**Comment by jhovgaard** [comment]
Fixed in build 135
