### ISSUE TITLE
Can drive the nissan in the new car dealer

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions-public#367]
Build 120

I can drive the new nissan in the new car dealer and can't buy the car.
[Build 120 Car Dealer BUG.txt](https://github.com/hovgaardgames/bigambitions-public/files/6906774/Build.120.Car.Dealer.BUG.txt)

https://user-images.githubusercontent.com/85610694/127637866-171bfff7-30ef-4a46-8a5d-6bd18924f884.mp4

**Comment by jhovgaard** [comment]
Fixed in build 121
