### ISSUE TITLE
Make it clear when the game is paused, you can't walk (UX)

### ISSUE THREAD

**Issue by niels-hubs** [hovgaardgames/bigambitions-public#368]
Hi,

First of all, awesome work! It's cool to see a couple of people making a switch from web development to game development.

I think that it should be a bit more clearer when the game is paused. I accidentally pressed the space bar in front of a store. So the game paused, tried to walk, but of course the game was paused. I searched for a couple of minutes what was going on and thought the game crashed. I would add a feature that if you try to walk for a couple of times while the game is paused, the game gives you feedback that you are stilled paused.

Maybe that would be something you could add.

Thanks again for being an example that everything is possible!

Kind regards,
Niels

**Comment by Gerwanese** [comment]
Transferred to community forum.
