### ISSUE TITLE
Bank loan when you enter minus

### ISSUE THREAD

**Issue by niels-hubs** [hovgaardgames/bigambitions-public#370]
Hi!

The bank is nasty! When you enter a loan with a minus in front of it, it takes your money. So does the bank pay me now with interests for the loan they took from me? I would assume it would work that way... but idk.

Kind regards,

Niels

**Comment by Gerwanese** [comment]
Good news: The bank will just borrow you 15,000 plus the amount you deposited.

[Build123-BankMinus.txt](https://github.com/hovgaardgames/bigambitions-public/files/6909433/Build123-BankMinus.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127696667-be2988cb-93d1-4644-b5b7-10ffdd9c7191.png)

**Comment by jhovgaard** [comment]
Fixed in build 131
