### ISSUE TITLE
False Price labels (Rounded integers)

### ISSUE THREAD

**Issue by Abdullamousawi** [hovgaardgames/bigambitions-public#372]
Build 123 (APLHA 5)

![image](https://user-images.githubusercontent.com/68964428/127698138-e3d45621-59c4-4f9c-a14b-32091d8a4148.png)

As you can see in the image, FreshFood (which I believe should be written as "Fresh Food" like in the objective window) is labeled $6 but the actual price is $5.5.

**Comment by adameg2305** [comment]
#334

**Comment by Gerwanese** [comment]
Duplicate of #334
