### ISSUE TITLE
Blurry View After Opening Bizview

### ISSUE THREAD

**Issue by amassivecont** [hovgaardgames/bigambitions-public#373]
After opening bizview and trying to enter the building at the same time the bizview menu opned and to close it i had to click close several times each time the menu became more opaque until i was left with a blurry view of the world 
![image](https://user-images.githubusercontent.com/88209621/127700341-b7191526-cb45-4fb8-b158-f374fdbecc52.png)

**Comment by adameg2305** [comment]
#356 @Gerwanese

**Comment by Gerwanese** [comment]
Duplicate of #356
