### ISSUE TITLE
Hiding buildings cause fps drop (for example corner of 4th street and 6th avenue)

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions-public#376]
Build 123.

The moment the building hides my fps from 140 to 40 and goes back up when the building unhides.

https://user-images.githubusercontent.com/85610694/127702737-0403e159-0928-4914-a820-a6fdd3f17ebe.mp4

[Build 123 FPs drop 4th street.txt](https://github.com/hovgaardgames/bigambitions-public/files/6909648/Build.123.FPs.drop.4th.street.txt)

**Comment by Gerwanese** [comment]
Not just that single building but others as well. Seems the larger the floor area of the building, the heavier the drop.

**Comment by jhovgaard** [comment]
Was fixed with the new outling system (Custom Pass based). Can't remember which build, long time ago 🥳
