### ISSUE TITLE
Buisness shown but hidden by another building

### ISSUE THREAD

**Issue by xaoseric** [hovgaardgames/bigambitions-public#381]
![20210730192739_1](https://user-images.githubusercontent.com/643544/127721404-cff7a21c-5072-4bdb-816f-087120e030fc.jpg)

There is a business overlapping and unable to click on it.
Build: Alpha 5 (123)

**Comment by Gerwanese** [comment]
That's the famous 24th Third Street - the "upper half" of number 26. :)
Duplicate of #97.
