### ISSUE TITLE
Negative loans of max value... 

### ISSUE THREAD

**Issue by Albrat32** [hovgaardgames/bigambitions-public#383]
You can not take a loan out that is large enough to do anything more than the game requires...
But you can enter a loan amount of -999999 and go completely bankrupt from giving the bank a loan.. 

It is pretty simple, walk in the bank. When they ask the amount you just enter - ...  Then as many 9's as you can.  You lost all money and they don't even pay you interest.

**Comment by tomvbj** [comment]
#370 Duplicate
