### ISSUE TITLE
When leaving building 5 on fifth avenue you get teleported out side of the playable area and cant return

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions-public#385]
Build 129.

When you leave the building you spawn at 4th avenue between 5th and 6th street.
When you reload you spawn back in the building but then when you leave you spawn outside of the playable area again.

https://user-images.githubusercontent.com/85610694/127736555-fbb69e89-21c5-445b-957e-94b5920814c5.mp4

![Big Ambitions 31_07_2021 12_08_53](https://user-images.githubusercontent.com/85610694/127736571-17aecf2e-83a2-4685-a18f-5862a55f25ee.png)
![Big Ambitions 31_07_2021 12_08_59](https://user-images.githubusercontent.com/85610694/127736573-00bb3793-f055-4ef4-971d-c507cfbcac91.png)
[Build 129 Wrong spawpoint BUG.txt](https://github.com/hovgaardgames/bigambitions-public/files/6911009/Build.129.Wrong.spawpoint.BUG.txt)

**Comment by Gerwanese** [comment]
[Build130-DoubleTheBuildingDoubleTheFun.txt](https://github.com/hovgaardgames/bigambitions-public/files/6911643/Build130-DoubleTheBuildingDoubleTheFun.txt)

I can verify that it happens with both buildings which are called 5 Fifthavenue (see #386).

**Comment by jhovgaard** [comment]
Fixed in build 132
