### ISSUE TITLE
When you rent building 5 on 5th avenue you rent 2 buildings 

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions-public#386]
Build 129.

It looks like the game thinks they are the same building while they are divided by a street

https://user-images.githubusercontent.com/85610694/127736791-e7b081f3-411a-40a2-9f62-c5f952f3bc5a.mp4

[Build 129 Building bug.txt](https://github.com/hovgaardgames/bigambitions-public/files/6911022/Build.129.Building.bug.txt)

Gerwanese if you can reproduce this can you make a better video as my video was to big :)

**Comment by Gerwanese** [comment]
Both show the same address and get rented together, so it's just one building with a private street going through. :)

[Build130-DoubleTheBuildingDoubleTheFun.txt](https://github.com/hovgaardgames/bigambitions-public/files/6911636/Build130-DoubleTheBuildingDoubleTheFun.txt)

https://user-images.githubusercontent.com/17579552/127748479-2eb2e56a-9d78-4528-8d95-40b4a563b3f5.mp4

**Comment by Gerwanese** [comment]
Not happening anymore in the meantime, replaced by other issues with the buildings. :)
