### ISSUE TITLE
Floor texture missing for one building in Firststreet

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#39]
One building in Firststreet is missing the floor texture and is showing pink instead.

![grafik](https://user-images.githubusercontent.com/17579552/116286229-4386c600-a78f-11eb-92c8-1f03d742c0b7.png)

![grafik](https://user-images.githubusercontent.com/17579552/116286252-4aadd400-a78f-11eb-8147-b2df4c356c35.png)

**Comment by jhovgaard** [comment]
Fixed in some build.
