### ISSUE TITLE
Build 130 econoview glitch

### ISSUE THREAD

**Issue by havoXD** [hovgaardgames/bigambitions-public#390]
Just put down cash register and shopping baskets and apparently I've already sold hot dogs in my shop.

![image](https://user-images.githubusercontent.com/55503913/127742271-b8b271a3-7047-40df-83d9-e6fb4de9618a.png)

**Comment by havoXD** [comment]
Edit: hot dogs in econoview has disappeared after loading the store with paper bags and cheap gifts.

**Comment by Gerwanese** [comment]
Confirmed. In my savegame it's the shop Gifty's in BizMan.

[Build130-TheyAreAllFakeShops.txt](https://github.com/hovgaardgames/bigambitions-public/files/6911694/Build130-TheyAreAllFakeShops.txt)

**Comment by jokoho48** [comment]
Fixed in Build 186
