### ISSUE TITLE
Hand truck shown as car on Voogle Maps

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#392]
Build 130

Hand trucks placed on the sidewalk are shown as cars on Voogle Maps.

[Build130-MyLittleCar.txt](https://github.com/hovgaardgames/bigambitions-public/files/6911709/Build130-MyLittleCar.txt)

https://user-images.githubusercontent.com/17579552/127749850-e45c389e-5640-48f2-b24b-54e381634c7e.mp4

**Comment by jokoho48** [comment]
Fixed in Build 190.
