### ISSUE TITLE
Can't buy paperbags at Metro Wholesale without using hand truck

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#393]
Build 130

At the Metro Wholesale you can't buy a box of paperbags. On queueing for checkout it will disappear. If you cancel, the box will be back in your hands.
If you then click on any other shelv (for example salad), the other box will be "inside" the container of 1000 paperbags. So the box of paperbags actually behaves like a single container.
This is only the case if you hold the box of paperbags in hands. If you use the hand truck, everything works correctly.

The same issue also occurs in the Drive-In Wholesales if you try to checkout by foot (on a car it works, just like the hand truck).

[Build130-NoPaperbagsForThisPerson.txt](https://github.com/hovgaardgames/bigambitions-public/files/6911744/Build130-NoPaperbagsForThisPerson.txt)

https://user-images.githubusercontent.com/17579552/127750452-617596c2-b0ad-400e-b811-37f5da0688c6.mp4

https://user-images.githubusercontent.com/17579552/127750504-bc5a7dec-dd50-4949-86a5-b4581d7a44f4.mp4

**Comment by jhovgaard** [comment]
Fixed in build 132
