### ISSUE TITLE
Tried to enter "The Green Salad" and I got teleported near 6th Street

### ISSUE THREAD

**Issue by ChrisMayhew** [hovgaardgames/bigambitions-public#405]
I tried to enter The Green Salad and got teleported near 6th Street which is currently out of bounds.. The only issue is I can't actually get back to the main part of the city to see if the same thing happens again.

**Comment by ChrisMayhew** [comment]
Build 130

**Comment by Gerwanese** [comment]
@ChrisMayhew Do you remember where The Green Salad was located? They are always generated at random places for every game, so unfortunately the name itself doesn't help in this case.
If it was in the building 5 Fifth Avenue (near the Metro Wholesales store), then it might be bug #385.

**Comment by ChrisMayhew** [comment]
Yes sorry it was on 5th Avenue... I wasn't aware that they randomly generated. It was upon entering for me though.

**Comment by Gerwanese** [comment]
I checked every building on 5th Avenue but they all work well for me.
I'll close the bug for now, hoping that your issue was the same building as in the other bug (which is fixed in the latest build). If you come across the problem again, we can reopen this issue.
