### ISSUE TITLE
Bank doesn't allow additional loan if the first one doesn't use the whole allowance

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#412]
Build 132

If I borrow less from the bank than I'm allowed, I can't borrow the rest right afterwards. The allowance will always be down to $0.

[Build130-Banksy.txt](https://github.com/hovgaardgames/bigambitions-public/files/6919361/Build130-Banksy.txt)

https://user-images.githubusercontent.com/17579552/127917919-e28f838a-7b0d-46b5-b320-3a1fc7347f7c.mp4

**Comment by jokoho48** [comment]
Fixed in the meanwhile. It allows to take Loans again but also removes the Loan intresst rate so if you get a $10 Loan you get 12$ removed from the allowed fee.
