### ISSUE TITLE
Bug in option screen (ultrawide monitor)

### ISSUE THREAD

**Issue by DarkRafas** [hovgaardgames/bigambitions-public#415]
Hi, 

I just found a bug with the fullscreen on/off switch, I'm using an ultrawide monitor, you can see the bug in the screenshot attached.

Regards
![Screenshot_1](https://user-images.githubusercontent.com/88396002/128054026-f7b25dde-0f54-43ab-9c35-41b4566817aa.png)

**Comment by DarkRafas** [comment]
I can confirm that its only on ultrawide resolutions.
![Screenshot_2](https://user-images.githubusercontent.com/88396002/128054334-fb1c6233-3d79-4816-a7ad-3b5d997eb023.png)

**Comment by Gerwanese** [comment]
I can confirm that the position varies, not just for ultrawide screens. With my 1920x1200 it's positioned wrong as well.
![grafik](https://user-images.githubusercontent.com/17579552/128073646-468f0de2-85ec-45da-a1a9-46b2917f1841.png)

**Comment by jokoho48** [comment]
Fixed in Build 181
