### ISSUE TITLE
5 potential bugs on my end:...

### ISSUE THREAD

**Issue by tikka56** [hovgaardgames/bigambitions-public#416]
Hi Jonas.

5 Things I noticed as bugs on my side:

1. The character always pauses movement when  as soon as he exits buildings onto the street. I usually have to wait 20 - 25 seconds before he starts moving and responding to my commands.

2. The loan interests and principle payback don't seem to be incorporated into expenses once you factor in payment, or is it already and the game doesn't mention it?

3. Nothing happens when your character completely runs out of energy/is starving... I don't know if this was meant for later on, but just wanted to point it out.

4. The mop is never made worse from use. Again, might not be until later.

5. Going back to point one about movement, it seems even more difficult to get the character to move on alley streets, as opposed to the open avenues.

BONUS: As a native English speaker, one thing I find jarring is the written English that Uncle Fred uses. A lot of it just doesn't sound right, and needs to be looked at by a native English speaker to sound more professional. I don't care how good a foreigners English is, some people just miss the really slangy American English terms or not hit them quite 100%.

**Comment by Gerwanese** [comment]
Hi @tikka56, thank you for your extensive feedback!

1. That's a known issue reported as bug #220 
2. Currently interest and payback don't exist for loans, that's still to do for a future release.
3. Consequences for empty energy / starving are planned for a future release as well.
4. Currently no item has any wear at all. The UI for the mop is a bit misleading, as "Condition" actually means "Cleanliness" (indicating how clean the floor is). If it's below 100% you can use the mop to clean the floor of your shop. The misleading wording is reported as bug #403.
5. It's a known issue on 3rd street that when walking the player often stops for a moment (bug #377). If you discover the effect for other streets as well, feel free to add a comment to the existing bug. I never experienced it in any other street yet myself.

For Uncle Fred's messages, if it needs improvement I guess the best way is to open a topic in the community forums (https://community.bigambitionsgame.com/) and discuss possible better alternatives there. Input from native speakers is always welcome and I agree that some slang every now and then be helpful to create the right atmosphere - although you always have to keep in mind that Uncle Fred is a successful business man and might use elevated diction.

I'll close this issue for now, as the bugs mentioned are already reported.
