### ISSUE TITLE
17th Fifth Avenue open with no business but available to rent

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#417]
Alpha 5 - Build 132 

Number 17 on fifth Avenue is open as a store, however, is completely empty and available to rent, as shown in the video below.

https://user-images.githubusercontent.com/44293115/128069865-2ec99a0c-7cf4-4f7c-b31b-1bc81a7b5b4d.mp4
[130175thOpen.txt](https://github.com/hovgaardgames/bigambitions-public/files/6926411/130175thOpen.txt)

**Comment by Gerwanese** [comment]
Integrated into #409
