### ISSUE TITLE
No car lights at night; breaking lights on taxis visible on front, top and back

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#42]
Only taxis have lights switched on at night. The taxi lights however are all red (front, back and taxi sign).
Taxis seem to have light on all day (although not very visible in sunlight), so probably there's no logic for this implemented at all yet.
![grafik](https://user-images.githubusercontent.com/17579552/116289669-f86eb200-a792-11eb-81c1-dbc9d81b5021.png)

**Comment by Gerwanese** [comment]
The taxi lights actually seem to be breaking lights, just visible on all sides of the cars instead of just backside.
If I get out of their way, the lights switch off.
![grafik](https://user-images.githubusercontent.com/17579552/116292217-bbf08580-a795-11eb-849d-04167fca9255.png)

**Comment by adameg2305** [comment]
A follow up to this, If you run into the taxi with either the character or a vehicle the lights turn off

**Comment by Gerwanese** [comment]
Fixed in the meantime
