### ISSUE TITLE
Expenses show double minus sign

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#421]
Build 136

When buying something, the animated money reduction will show the purchase value with two minus signs:

[Build136-DoubleMinus.txt](https://github.com/hovgaardgames/bigambitions-public/files/6933766/Build136-DoubleMinus.txt)

![grafik](https://user-images.githubusercontent.com/17579552/128239560-c5a738f2-9221-4617-88f8-2f8f07ce455b.png)

**Comment by jhovgaard** [comment]
Fixed in build 173
