### ISSUE TITLE
Clicking "Eat" button of paperbag items at the lower half will not do anything

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#422]
Build 136

When trying to eat food from a paperbag through clicking the "Eat" button, it won't work if you click the lower half of the button.

[Build136-DoubleMinus.txt](https://github.com/hovgaardgames/bigambitions-public/files/6933787/Build136-DoubleMinus.txt)

https://user-images.githubusercontent.com/17579552/128240054-be36687b-b8f8-460a-8d01-38bd3f69d377.mp4

**Comment by jokoho48** [comment]
Fixed in Build 186.
