### ISSUE TITLE
Invisible walls at car dealer

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#423]
Build 136

At the car dealer there seem to be at least two invisible walls around the van, just leaving a small gap in between them (so the van is still accessible but the player can't walk a straight line).

[Build136-WalledCarDealer.txt](https://github.com/hovgaardgames/bigambitions-public/files/6933874/Build136-WalledCarDealer.txt)

https://user-images.githubusercontent.com/17579552/128241764-b3381853-af04-4f91-af9b-985a1b726cb0.mp4

**Comment by jhovgaard** [comment]
Fixed in build 140 ish
