### ISSUE TITLE
Drive-In Wholesales can't be accessed by car anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#424]
Build 136

The Drive-In Wholesales turned into a Drive-To Wholesales, as the "In" doesn't work anymore. You can still access it by foot or with a hand truck but not with a car.

[Build136-DriveInDrivesMeOff.txt](https://github.com/hovgaardgames/bigambitions-public/files/6933901/Build136-DriveInDrivesMeOff.txt)

https://user-images.githubusercontent.com/17579552/128242249-62d9f561-03ca-4b19-8df5-9663d6267867.mp4

**Comment by jhovgaard** [comment]
Fixed in build 138
