### ISSUE TITLE
Drive-In Wholesales charges single item price for boxes

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#425]
Build 136

The Drive-In Whoesales store charges the price of a single item for boxes.

[Build136-DriveInSpecialDiscount.txt](https://github.com/hovgaardgames/bigambitions-public/files/6933939/Build136-DriveInSpecialDiscount.txt)

https://user-images.githubusercontent.com/17579552/128243147-d52e445a-eae6-4bc6-82dd-07c6b2dc915e.mp4

**Comment by jhovgaard** [comment]
Fixed in build 138
