### ISSUE TITLE
EconoView: Van purchase and Drive-In purchases with wrong labels in Last Transactions

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#426]
Build 136

In the Last Transactions list of EconoView, a purchased van shows as "VehicleName (TMPro.TextMeshProUGUI)" and all purchases from Drive-In Wholesales (different items) show as "Purchase fromTemporary Building Data" (besides the wrong business name, note the missing space after "from").

![grafik](https://user-images.githubusercontent.com/17579552/128243575-bffbaba0-0717-4229-a753-6104c5430d65.png)

[Build136-WalledCarDealer.txt](https://github.com/hovgaardgames/bigambitions-public/files/6933971/Build136-WalledCarDealer.txt)

[Build136-DriveInSpecialDiscount.txt](https://github.com/hovgaardgames/bigambitions-public/files/6933969/Build136-DriveInSpecialDiscount.txt)

**Comment by jokoho48** [comment]
Fixed in Build 185
