### ISSUE TITLE
Can't pick up shopping basket at El Gato

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#427]
Build 136

It's not possible anymore to pick up a shopping basket and buy food at El Gato.

[Build136-ElGatoNotElBasket.txt](https://github.com/hovgaardgames/bigambitions-public/files/6933993/Build136-ElGatoNotElBasket.txt)

https://user-images.githubusercontent.com/17579552/128244281-86340179-b65e-4050-af76-01206c472b87.mp4

**Comment by jhovgaard** [comment]
Fixed in build 137
