### ISSUE TITLE
Wrong pickup location for all supermarket items

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#428]
Build 136

When picking up items (shopping basket or food), the pickup location is wrong and always seems to be a certain distance in front of the items.
This applies only to supermarkets, but to all of them.

[Build136-PickMeImAnItem.txt](https://github.com/hovgaardgames/bigambitions-public/files/6934021/Build136-PickMeImAnItem.txt)

https://user-images.githubusercontent.com/17579552/128245046-baada222-0451-4137-87fc-8fe69cf284cf.mp4

**Comment by jhovgaard** [comment]
Fixed in build 139
