### ISSUE TITLE
Van wheels don't throw shadow

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#43]
It seems as if the wheels of the vans are ignored when drawing the shadow. As a result, there's a lighted area around/"behind" the wheels giving an appearance as if the cars would not be on the ground (especially the back wheel). You can see that the sunlight/shadow marker seems to follow the wheel well borders.
For cars it might be the same but just not visible because the wheel wells are too small.
![grafik](https://user-images.githubusercontent.com/17579552/116290847-34eedd80-a794-11eb-9674-a54224c991c5.png)

**Comment by jhovgaard** [comment]
Fixed in build 13
