### ISSUE TITLE
Transparent Building

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#430]
Alpha 5 - Build 138 

the main Building for El Gato Foods has become transparent in the latest build. 
![T52PDE](https://user-images.githubusercontent.com/44293115/128353215-3bce697d-4ae6-4b9a-9237-d7ef9714327e.png)
 Also, another issue with the same building is reported in #197

**Comment by adameg2305** [comment]
Same issue with 23rd street, also mentioned now in #197

**Comment by jhovgaard** [comment]
El Gato Foods fixed in build 138
