### ISSUE TITLE
Placing grid in first apartment not well set / Standard fridge not rotatable

### ISSUE THREAD

**Issue by Fabi-Gaming-Lounge** [hovgaardgames/bigambitions-public#431]
The placement grid in the first apartment is not set optimally. Thus, for example, the fridge can not be placed completely against the wall because it sticks out a bit into the grid.

![image](https://user-images.githubusercontent.com/63157166/128369460-bd6662b6-f0e7-43d9-b3b3-ff01f7efe84b.png)

Small note it would also be cool if you could turn the fridge.

**BUILD: 138**

**Comment by Gerwanese** [comment]
@Fabi-Gaming-Lounge Thank you for the report. The bug is already reported as #234, so I'll close this issue.
When you're in placement mode you can turn the fridge through right mouse click.
