### ISSUE TITLE
Cash Register shows "STOCK_COUNT" after Completing shift

### ISSUE THREAD

**Issue by Fabi-Gaming-Lounge** [hovgaardgames/bigambitions-public#432]
The cash register label displays the message "STOCK_COUNT" at the end of the work shift at the El Gato Foods supermarket.

![image](https://user-images.githubusercontent.com/63157166/128373859-418b4a13-f994-48d7-86dd-8734b181e955.png)

-Build 138 A5

**Comment by Gerwanese** [comment]
Issue is already included in bug #227, so I'll close here
