### ISSUE TITLE
No Character limit for business names

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#433]
Alpha 5 - Build 139

There is no character limit when the user is typing in a new business name, otherwise this is what it looks like:
![JEC0xf](https://user-images.githubusercontent.com/44293115/128378412-659f1e65-661b-42af-83bc-081e3596af32.png)
![wOUWms](https://user-images.githubusercontent.com/44293115/128378559-0a7717a4-d4b2-4355-9788-7efaed4cebfb.png)

**Comment by Gerwanese** [comment]
While this is for sure a bug, I have to admin that shop signboards look pretty cool with long names.

[Build136-ILongForThisName.txt](https://github.com/hovgaardgames/bigambitions-public/files/6941169/Build136-ILongForThisName.txt)

![grafik](https://user-images.githubusercontent.com/17579552/128409335-02b85320-29c2-4433-a35f-b37720229d4d.png)

**Comment by jokoho48** [comment]
Fixed in Build 191. The character limit is set to 20 for now, but as we don't have any indications of what the limit is or when the limit is reached.
