### ISSUE TITLE
Double holding hand truck in Appliance Store

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#434]
Alpha 5 - Build 139

You can hold two hand trucks at the same time, and when you park the hand truck you have a handtruck inside you until you leave the building.

https://user-images.githubusercontent.com/44293115/128383252-5754df21-7500-4c87-af92-f70fbfbe14da.mp4

**Comment by Gerwanese** [comment]
I guess old people will be happy about this... :)

[Build136-HandyTrucky.txt](https://github.com/hovgaardgames/bigambitions-public/files/6941349/Build136-HandyTrucky.txt)

**Comment by Gerwanese** [comment]
Doesn't happen anymore in build 184.

**Comment by samer0n** [comment]
This issue is occurring again in build 350, encountered it in the IKEA store 

https://user-images.githubusercontent.com/99119499/154040451-3c03f668-bc21-44b1-a995-7345a667fef4.mp4

@Gerwanese

**Comment by Gerwanese** [comment]
@samer0n Issue #786 is the new one for this bug. :)
