### ISSUE TITLE
You can still access phone apps while time warping

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#435]
Alpha 5 - Build 139

While sleeping you can still open apps on the phone, as shown in the video you can still open Bizman and interact with it while sleeping.

https://user-images.githubusercontent.com/44293115/128384917-cb10c052-60b1-4651-864c-fcc30db7874c.mp4

**Comment by Gerwanese** [comment]
[Build136-OneOfEverything.txt](https://github.com/hovgaardgames/bigambitions-public/files/6941136/Build136-OneOfEverything.txt)

**Comment by jokoho48** [comment]
Fixed in Build 181
