### ISSUE TITLE
Start a new business - Pick a logo not working

### ISSUE THREAD

**Issue by Datenschmutz** [hovgaardgames/bigambitions-public#438]
Build - 139

The "Pick a logo" button does not work.

![grafik](https://user-images.githubusercontent.com/63157166/128430510-daa9abe5-e859-4b3b-adc9-183f4ecbdb47.png)

**Comment by Gerwanese** [comment]
Hi @Datenschmutz, adding logos to businesses is not yet implemented, it will be added in a future version.
