### ISSUE TITLE
Add city bounding wall colliders

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#44]
It's possible to drive through the side and back walls of the drive-in wholesales store.
When entering through those walls and then leaving through the front doors, you actually enter the building (probably because the door interaction switches between in and out, no matter from which direction you hit it).
![grafik](https://user-images.githubusercontent.com/17579552/116291465-e55ce180-a794-11eb-878e-594f2344c6a8.png)

**Comment by ChrisB-M** [comment]
On the same theme, there are no boundaries on some parts of the map. You can literally drive off the edge of the map

![floor](https://user-images.githubusercontent.com/6843892/116361927-6ea5ff80-a7f9-11eb-8fab-a1db6535f8f3.PNG)

**Comment by ChrisB-M** [comment]
Voogle Maps thinks I have driven into a black hole...

![voogle maps black hole](https://user-images.githubusercontent.com/6843892/116362641-2c30f280-a7fa-11eb-8282-70e215ee2625.PNG)

**Comment by jhovgaard** [comment]
Fixed in build 49. Added temporary invisible walls for avoiding players falling off ground
