### ISSUE TITLE
Opening hours sliders don't work anymore when start and end are both set to 24:00

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#442]
Build 139

If you set both start and end for the opening hours sliders to 24:00, you can't change them anymore as the "closing" one is on top and can't be set below "opening".

If it happens for a single day only, you can fix it by using the "global" slider. If it happens to the "global" slider however, you can't fix it and have to save/reload the game.

[Build139-SlidersNotSlidingAnymore.txt](https://github.com/hovgaardgames/bigambitions-public/files/6945335/Build139-SlidersNotSlidingAnymore.txt)

https://user-images.githubusercontent.com/17579552/128506821-d041ce5e-0941-4857-955e-d69cc7aa3da9.mp4

**Comment by jokoho48** [comment]
Fixed in Build 186
