### ISSUE TITLE
Buildings initially not hiding when leaving them

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#445]
Build 143

Right after leaving a building, it will not hide if it's in front of the player.
Once you turn the camera all the way around to the other side, it will fix itself and afterwards hide properly (until you enter and exit again).

[Build143-BuildingsNotHiding.txt](https://github.com/hovgaardgames/bigambitions-public/files/6946405/Build143-BuildingsNotHiding.txt)

https://user-images.githubusercontent.com/17579552/128533738-c87a320d-1244-46b3-9a16-b42c6842a338.mp4

**Comment by jhovgaard** [comment]
Fixed in build 160
