### ISSUE TITLE
ClassicCheapMaleClothing: Market price $0

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#446]
Build 143

The market price for classic cheap male clothing is $0. Unfortunately customers are still not willing to pay this horrendous price.

[Build143-FreeJeans.txt](https://github.com/hovgaardgames/bigambitions-public/files/6946970/Build143-FreeJeans.txt)

![grafik](https://user-images.githubusercontent.com/17579552/128546442-b837961a-946b-4187-8c53-a4cb7f8cd0ea.png)

![grafik](https://user-images.githubusercontent.com/17579552/128546226-c107960a-5191-4dde-9e4e-d8eb4fc3cfae.png)

**Comment by jhovgaard** [comment]
Fixed in build 152
