### ISSUE TITLE
Forklift always showing 0 cargo

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#448]
Build 151

The forklift is always showing "Cargo loaded: 0/0" even when it's loaded with a pallet.

[Build151-Forklift-CargoEmpty.txt](https://github.com/hovgaardgames/bigambitions-public/files/6949206/Build151-Forklift-CargoEmpty.txt)

![grafik](https://user-images.githubusercontent.com/17579552/128602956-3b3fd194-52ab-4b23-a9d9-1d685a5da44d.png)

**Comment by jokoho48** [comment]
Fixed in Build 186
