### ISSUE TITLE
Possible to break vehicle parking rules by moving it out of parking zone

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#45]
If you park the vehicle at the very border of allowed parking (as much outside as possible) and then run into it (probably also works with driving a car into it), thus moving it a bit further out - so it's actually not inside the allowed parking anymore - once you enter the vehicle, you're allowed to park anywhere at any speed.
Only if you driv on / cross a regular parking zone again, the status is reset and the normal rules apply again (parking only in parking zone and only when stopped).

https://user-images.githubusercontent.com/17579552/116296391-771b1d80-a79a-11eb-856a-9863b7edff47.mp4

**Comment by jhovgaard** [comment]
Related to #61

**Comment by jhovgaard** [comment]
Update to self: Make parked vehicles kinematic. We never want them to move.

**Comment by jhovgaard** [comment]
Fixed in build 67 by allowing parking everywhere 😎
