### ISSUE TITLE
Multiple salad bars make employee choose the wrong one

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#450]
Build 153

When having multiple salad bars, the employees seem to pick a random one.
It doesn't matter whether it's filled or not. If the salad bar is empty, the employee will walk there and immediately return again without selling the salad.

Employees should instead always opt for the nearest non-empty salad bar (and of course the same for other types like drinks fridge).

[Build153-MultiSalad.txt](https://github.com/hovgaardgames/bigambitions-public/files/6983731/Build153-MultiSalad.txt)

https://user-images.githubusercontent.com/17579552/129386597-7470a85c-1d41-41f7-956f-98a017b80b6a.mp4

**Comment by jokoho48** [comment]
Fixed in build 180

**Comment by Gerwanese** [comment]
Reopening: In build 181, the employee always chooses the nearest salad bar, but not the nearest non-empty. So if the nearest one is empty, but another one has salad in it, he will still choose the empty one.

**Comment by jokoho48** [comment]
Fixed in build 182
