### ISSUE TITLE
BizMan: "Best selling products" lists products that were never sold

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#451]
Build 153

After 7 days of business operation, the "best selling products" for the last 7 days in BizMan will show products that were never sold.
In this case the gift shop doesn't have a drinks fridge but best selling products shows 3 SodaCan and 12 CheapGift.
The 12 for CheapGift can't be correct as well, I have been selling 173 during those 7 days (even the daily average would be almost 25).

[Build153-ISellEverythingEvenIfNotAvailable.txt](https://github.com/hovgaardgames/bigambitions-public/files/6994797/Build153-ISellEverythingEvenIfNotAvailable.txt)

![grafik](https://user-images.githubusercontent.com/17579552/129616451-4f182c79-b743-49c1-8173-7d22d2f14580.png)

**Comment by jokoho48** [comment]
Fixed in Build 186
