### ISSUE TITLE
Interacting with objects possible while BizMan is open

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#453]
Build 153

While BizMan is open, you can still interact with objects "behind" it (in this case the fridge).

[Build153-InteractBehindBizMan.txt](https://github.com/hovgaardgames/bigambitions-public/files/7017180/Build153-InteractBehindBizMan.txt)

https://user-images.githubusercontent.com/17579552/130129529-7efdcaeb-c5db-4505-ab45-7b5ed2bf0ff5.mp4

**Comment by jokoho48** [comment]
Fixed in Build 181
