### ISSUE TITLE
MyEmployees view not refreshed after reopening

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#454]
Build 153

When reopening the MyEmployees app, the view is not refreshed initially.
This is obvious when you train an employee: It will still show him in training even after more than one day. Only after clicking that employee again, the view will update.

[Build153-InteractBehindBizMan.txt](https://github.com/hovgaardgames/bigambitions-public/files/7017210/Build153-InteractBehindBizMan.txt)

https://user-images.githubusercontent.com/17579552/130130115-6543af22-fcb1-4441-a691-e9fbff2ffb68.mp4

**Comment by jokoho48** [comment]
Fixed in Build 181
