### ISSUE TITLE
Employee can be trained to more than 100%

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#456]
Build 153

When training an employee who is >90% already, he will end up over 100%.

[Build153-OvertrainedEmployee.txt](https://github.com/hovgaardgames/bigambitions-public/files/7017255/Build153-OvertrainedEmployee.txt)

https://user-images.githubusercontent.com/17579552/130131382-b8304fbe-f085-49fe-8868-a3e77e1bb175.mp4

**Comment by jhovgaard** [comment]
Fixed in build 173
