### ISSUE TITLE
Recruitment Agency ignoring age filter

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#457]
Build 153

The recruitment agency ignores age filters and offers candidates of any age.

[Build153-RecruitWrongAge.txt](https://github.com/hovgaardgames/bigambitions-public/files/7017339/Build153-RecruitWrongAge.txt)

https://user-images.githubusercontent.com/17579552/130133063-f108c714-32ab-4d64-baa6-54f6cd80f27a.mp4

**Comment by jhovgaard** [comment]
Fixed in build 173
