### ISSUE TITLE
Voogle Maps: Unpausing possible after opening and closing BizMan

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#458]
Build 165

Usually it's not possible to unpause the game while Voogle Maps is opened. If you open and close the BizMan out of the map however, unpausing the game will be possible afterwards.

[Build165-VoogleMapsUnpauseAfterOpeningBizMan.txt](https://github.com/hovgaardgames/bigambitions-public/files/7041541/Build165-VoogleMapsUnpauseAfterOpeningBizMan.txt)

https://user-images.githubusercontent.com/17579552/130674589-02529d01-3218-4382-9a8c-5a1a18b935c4.mp4

**Comment by jokoho48** [comment]
Fixed in build 180
