### ISSUE TITLE
Parking zone not working in outskirts of Fourthstreet

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#46]
In the outskirts of Fourthstreet (away from houses) it's not possible to park on the parking zone. See location of mouse pointer on Voogle Maps.

![grafik](https://user-images.githubusercontent.com/17579552/116297367-7cc53300-a79b-11eb-9fdc-85006e1d5176.png)

![grafik](https://user-images.githubusercontent.com/17579552/116297425-88b0f500-a79b-11eb-9959-79c8d8291db2.png)

**Comment by jhovgaard** [comment]
Fixed in build 49
