### ISSUE TITLE
Subway: Impossible to select HellsKitchenStation2

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#462]
Build 169

It's impossible to select HellsKitchenStation2 (at the corner 3rd Ave / 1st Str) on Voogle Maps as it's behind a building.
Also if you're standing right in front of it, you can only select it when turning the map. Otherwise only the building behind it will be selected (see second savegame / video).
Additionally the entrance is off the actual location (see #461).

[Build169-HellsKitchenStation2.txt](https://github.com/hovgaardgames/bigambitions-public/files/7061515/Build169-HellsKitchenStation2.txt)

[Build169-GarmentDistrictStation2Entrance.txt](https://github.com/hovgaardgames/bigambitions-public/files/7061499/Build169-GarmentDistrictStation2Entrance.txt)

https://user-images.githubusercontent.com/17579552/131005440-4b822cd3-f049-4db4-8694-ada0309fa207.mp4

https://user-images.githubusercontent.com/17579552/131005928-358b2751-188f-42b6-90aa-94d215ad11bb.mp4

**Comment by jokoho48** [comment]
Fixed in Build 186
