### ISSUE TITLE
Subway fare charged without taking a ride

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#467]
Build 172

When clicking on a subway station, the fare is immediately charged even if I close the map and don't take a ride.

[Build172-SubwayChargedWithoutRide.txt](https://github.com/hovgaardgames/bigambitions-public/files/7062687/Build172-SubwayChargedWithoutRide.txt)

https://user-images.githubusercontent.com/17579552/131035021-ead92f3c-6d00-4bf1-bf16-c394f73bdead.mp4

**Comment by jokoho48** [comment]
Fixed in build 180
