### ISSUE TITLE
Voogle Maps: Missing street names

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#469]
Build 172

Several street names are missing:
- Broadway Street
- Fourth Avenue
- Extension of Broadway Street after the roundabout
- 11th Street

![grafik](https://user-images.githubusercontent.com/17579552/131035755-80d4be31-5578-47c4-bd5d-ec64dbbf103e.png)

![grafik](https://user-images.githubusercontent.com/17579552/131035804-d159e865-1ed3-4b3e-bfe9-e9059556915a.png)

![grafik](https://user-images.githubusercontent.com/17579552/131035867-f56ff06b-1d56-4a27-a9f5-6cbb00806dd5.png)

![grafik](https://user-images.githubusercontent.com/17579552/131035932-1fba774a-b120-4c1b-b698-1694419509f7.png)

**Comment by jokoho48** [comment]
Fixed in Build 182
