### ISSUE TITLE
Several street labels at wrong positions

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#47]
Build 66

See red marked labels in the following three screenshots.
Besides, the diagonal streets are all without label.

![grafik](https://user-images.githubusercontent.com/17579552/122655997-3ff03980-d157-11eb-91bf-6d2ca5ed0d2d.png)

![grafik](https://user-images.githubusercontent.com/17579552/122656012-61e9bc00-d157-11eb-86d3-2b0245ad0310.png)

![grafik](https://user-images.githubusercontent.com/17579552/122656038-90679700-d157-11eb-8aa1-807b3ac022f9.png)

**Comment by jokoho48** [comment]
Fixed in the meanwhile
