### ISSUE TITLE
Voogle Maps "jumps" when dragging after selecting buildings

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#472]
Build 172

After selecting buildings, if you try to drag Voogle Maps, it will regularly jump in the wrong direction.

Observations made:
- If you have selected a building on top and then click on another building at the bottom, the map will jump north.
Similar if you have selected a building at the bottom and click another near the top, the map will jump south.
But it seems to depend on the position of the second clicked building on the map, it's not always the same.
- It happens if you click a building (dialog shows up), then click another building (dialog shows up) and then click on the area where the dialog of the first building has been before (even if you click on a street).
It seems that the map will be moved by the distance of the two dialogs.
For example if the first dialog was at coordinates 2 , 2 and the second at 6 , 8 - then it seems when clicking on the 2 , 2 again, it will move you +4 , +6 to location 10, 14.
Feels like the map is trying to center on the clicked area, but wrong sign is used (- instead of + or vice versa)

https://user-images.githubusercontent.com/17579552/130675058-d8a9bb07-26ab-4b77-8bd9-23a2bab75859.mp4

**Comment by jokoho48** [comment]
Fixed in build 180
