### ISSUE TITLE
Map Icons: Own business icon stays even after terminating business

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#477]
Build 172

After terminating my business and cancelling the rental contract, the building is still shown with the "business" icon in city view as well as on the map.

[Build172-26FifthAvenue.txt](https://github.com/hovgaardgames/bigambitions-public/files/7063077/Build172-26FifthAvenue.txt)

https://user-images.githubusercontent.com/17579552/131045253-bcb128ba-5887-4103-8fb7-503baa422f67.mp4

**Comment by jokoho48** [comment]
Fixed in Build 186
