### ISSUE TITLE
Stone floor not walkable at corner Thirdavenue / Thirdstreet

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#48]
The grey stone floor triangle in front of the corner building Thirdavenue / Thirdstreet can not be walked on.

![grafik](https://user-images.githubusercontent.com/17579552/116297809-f6f5b780-a79b-11eb-8d7a-4184d5ae1595.png)

![grafik](https://user-images.githubusercontent.com/17579552/116297875-0bd24b00-a79c-11eb-99d7-79f4ac1bb3a2.png)

**Comment by jokoho48** [comment]
Fixed in the mean while.
