### ISSUE TITLE
Fast Food Restaurant sells empty paperbag if food is not available

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#480]
Build 172

If the requested food is not available, customers at the fast food restaurant will get an empty paper bag.
The employee will still walk to the empty machines and "pretend" to fill something into the paperbag.

[Build172-SellEmptyPaperbag.txt](https://github.com/hovgaardgames/bigambitions-public/files/7063135/Build172-SellEmptyPaperbag.txt)

https://user-images.githubusercontent.com/17579552/131047073-f7101028-12f0-484e-af4c-01b86a50eb9a.mp4

**Comment by jokoho48** [comment]
Fixed in Build 185
