### ISSUE TITLE
Broken building: 21 Fourth Avenue

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#481]
Build 172

[Build172-21FourthAvenueBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7066240/Build172-21FourthAvenueBroken.txt)

https://user-images.githubusercontent.com/17579552/131113132-a2a7bdb2-3899-44ac-bf54-9ba186ead20a.mp4

**Comment by jhovgaard** [comment]
Fixed in build 173
