### ISSUE TITLE
Residential Building shows info of last selected commercial building in BizMan

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#483]
Build 172

When opening the BizMan of a residential building, it will show the information of the last selected commercial building on the right side.

[Build172-ResidentialWrongInfo.txt](https://github.com/hovgaardgames/bigambitions-public/files/7066324/Build172-ResidentialWrongInfo.txt)

https://user-images.githubusercontent.com/17579552/131114635-34647168-2750-4d76-9dca-ea57176f84e4.mp4

**Comment by jhovgaard** [comment]
Fixed in build 173
