### ISSUE TITLE
Building broken: 30 Third Street

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#484]
Build 172

[Build172-30ThirdStreetBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7066351/Build172-30ThirdStreetBroken.txt)

https://user-images.githubusercontent.com/17579552/131115159-1b71e07a-2483-4d3b-867f-6ebc9c0b2d6a.mp4

**Comment by jhovgaard** [comment]
Fixed in build 173
