### ISSUE TITLE
Building broken: 20 Third Street

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#485]
Build 172

[Build172-20ThirdStreetBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7066361/Build172-20ThirdStreetBroken.txt)

https://user-images.githubusercontent.com/17579552/131115468-1c14bd12-3eb1-4f1b-b94e-fc7952252cb7.mp4

**Comment by jhovgaard** [comment]
Fixed in build 173
