### ISSUE TITLE
Picking up king-sized bed leaves it unplaceable

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#489]
Build 173

When picking up and already placed king-sized bed, there's no chance to place it anymore. This seems to come from the red triangle moving far away from the bed and always being outside of the apartment.

[Build173-KingSizedBedBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7068093/Build173-KingSizedBedBroken.txt)

https://user-images.githubusercontent.com/17579552/131152862-2363f519-b38f-4491-ac2b-e2edbc78bcca.mp4

**Comment by jhovgaard** [comment]
Fixed in build 187
