### ISSUE TITLE
Click to skip Prelogue only works in certain areas

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#49]
When starting a new game and the prologue starts, when it's on the first message you cant click to skip ahead, however when the second one loads you then can.

**Comment by Gerwanese** [comment]
It actually works on first message as well. In works whenever you click on the text message (or the place where a future text message will appear) but not in between or in any other area of the screen.

**Comment by jhovgaard** [comment]
Fixed in build 13
