### ISSUE TITLE
MultiPurposeChair can't be placed in apartment

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#491]
Build 173

When holding a MultiPurposeChair, the "Place" button doesn't do anything.

[Build173-MultiPurposeChairBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7068221/Build173-MultiPurposeChairBroken.txt)

https://user-images.githubusercontent.com/17579552/131156121-79c65bd9-6943-4c0d-b688-44099c6bf3fe.mp4

**Comment by jokoho48** [comment]
Fixed in 181
