### ISSUE TITLE
Ikea offers two types of OfficeDesk1 but only one is sold

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#492]
Build 173

At Ikea you can find two types of OfficeDesk1, a dark one and a light one. No matter which of these you buy, you'll always have a light one in the end.

[Build173-Ikea.txt](https://github.com/hovgaardgames/bigambitions-public/files/7068360/Build173-Ikea.txt)

![grafik](https://user-images.githubusercontent.com/17579552/131159329-60d1c5d6-854c-4745-89fc-3fd798c7cb29.png)

![grafik](https://user-images.githubusercontent.com/17579552/131159345-307edb69-79c1-4631-8722-89cd63d52d01.png)

**Comment by jokoho48** [comment]
Fixed in Build 185
