### ISSUE TITLE
GPU is constantly at 100% utilization

### ISSUE THREAD

**Issue by RamonRobben** [hovgaardgames/bigambitions-public#493]
Hi, I would like to request the feature to be able to limit the FPS.
Currently I have a Ryzen 9 5950X with an RTX 3070 running at full speed outputting between 400-500FPS at Ultra Quality (1920x1080) resolution. I'd rather have an FPS limiter so that my room doesn't get so hot and also my computer doesn't get so hot / loud while playing the game. See attached screenshot of my FPS.

FPS limiter would be nice with presets like 60FPS, 120FPS 144FPS and custom input.

Here is a picture of the FPS. And of my GPU utilization while in the main menu.

![image](https://user-images.githubusercontent.com/12982618/131165928-3b8d3be2-1693-4d7b-b851-45d6ffcab6a4.png)
![image](https://user-images.githubusercontent.com/12982618/131166618-35095087-33c6-4d83-baa0-f682f0c33353.png)

Currently I am running on Alpha 5 (build 153)

**Comment by jokoho48** [comment]
Fixed in Build 181
