### ISSUE TITLE
New icons for apartment and businesses visible in phone apps

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#498]
Build 175

The new icons for owned apartments and businesses are still visible when opening phone apps.

[Build175-Icons.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071393/Build175-Icons.txt)

https://user-images.githubusercontent.com/17579552/131229443-8b289bfa-35c9-4d9f-a084-c3d2a62b4561.mp4

**Comment by jokoho48** [comment]
Fixed in build 180
