### ISSUE TITLE
Voogle Maps: Can't select "Show Details" or "Set Destination" if buildings too close to each other

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#50]
On third street especially you cant select any building properly as when you hover over the building you want you then cant select "see details" or "set  destination" as it then shows the building below or above

**Comment by Gerwanese** [comment]
Verified - some buildings work correctly in Voogle Maps, but if they're too close to each other, it will immediately select the next building.

**Comment by jhovgaard** [comment]
Related to #60

**Comment by jhovgaard** [comment]
Fixed by new city map
