### ISSUE TITLE
Subway stations focus area too large

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#500]
Build 175

When hovering over the area above any subway entrance, the station will get selected instead of the building. So the focus area of subway stations extends way above them.

Additionally for HellsKitchenStation2, you can't walk on the floor in front of the building as it's blocked (so you can't walk into the subway station properly).

[Build175-3ThirdAvenueBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071431/Build175-3ThirdAvenueBroken.txt)

https://user-images.githubusercontent.com/17579552/131229993-0dc418c5-d9a8-4f47-b7e6-2a97a6003105.mp4

**Comment by CoolGingerGinger** [comment]
Focus area also too large when rotated, making it so if you click in the middle of the street it instead takes you to the subway. (Build 184)

https://user-images.githubusercontent.com/88410729/131598989-b833b47b-b618-44d3-83c4-4cdd00647093.mp4

**Comment by jokoho48** [comment]
Fixed in Build 186
