### ISSUE TITLE
13/15 Third Avenue can be rented and 15 entered without renting

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#501]
Build 175

Both 13 and 15 Third Avenue can be rented.
15 Third Avenue is shown as "open" even when not rented and can be entered, looking like the Business School but without room doors (rooms can't be entered though).
13 Third Avenue can't be entered, even if it's rented.

[Build175-1315ThirdAvenue.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071435/Build175-1315ThirdAvenue.txt)

https://user-images.githubusercontent.com/17579552/131230131-c5999b97-16d3-48d0-a333-5f32ad4f929c.mp4

**Comment by jhovgaard** [comment]
Impacted by the disabling of office buildings earlier.
Fixed in build 194
