### ISSUE TITLE
Generated Jewelry Store: Empty shelves show label "ExpensiveGift" instead of "CheapJewelry"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#503]
Build 175

In a generated jewelry store, the empty shelves all show "ExpensiveGift".

[Build175-JewelryStoreWrongLabels.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071465/Build175-JewelryStoreWrongLabels.txt)

![grafik](https://user-images.githubusercontent.com/17579552/131230392-c89e7482-6a24-42fc-8b3f-f6b162f1ba2e.png)

**Comment by jokoho48** [comment]
Fixed in Build 182
