### ISSUE TITLE
Broken Building: 25 Third Street

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#504]
Build 175

Can't be entered, additionally showing as apartment.

[Build175-25ThirdStreetBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071470/Build175-25ThirdStreetBroken.txt)

https://user-images.githubusercontent.com/17579552/131230428-b642d660-adca-4c0a-90db-edc916ead732.mp4

**Comment by jhovgaard** [comment]
Fixed in build 177
Requires new savegame
