### ISSUE TITLE
Wrong building: 3 Fifth Avenue

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#506]
Build 175

3 Fifth Avenue is shown as Warehouse on the map. It can be rented. When entering, it will show as shop building and you can start a business there.

[Build175-FifthAvenueIssues.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071487/Build175-FifthAvenueIssues.txt)

https://user-images.githubusercontent.com/17579552/131230777-839b60bb-63c4-49a1-9c5b-ab1c05918412.mp4

**Comment by jhovgaard** [comment]
Fixed in build 194
