### ISSUE TITLE
Broken Building: 2 Sixth Avenue

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#508]
Build 175

2 Sixth Avenue can be rented, but when entering you'll end up in void.

[Build175-2SixthAvenue.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071498/Build175-2SixthAvenue.txt)

https://user-images.githubusercontent.com/17579552/131230949-74de9f34-7a2c-4318-80bc-98d2c7a1f64e.mp4

**Comment by jhovgaard** [comment]
Fixed in build 177
Requires new savegame
