### ISSUE TITLE
Broken Building: 9 Fifth Avenue

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#509]
Build 175

9 Fifth Avenue can get rented and entered but you'll end up in void.

[Build175-9FifthAvenue.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071502/Build175-9FifthAvenue.txt)

https://user-images.githubusercontent.com/17579552/131231137-fb571b89-7f54-4212-b6a7-1ec052bb5e0f.mp4

**Comment by jhovgaard** [comment]
Fixed in build 177
Requires new savegame
