### ISSUE TITLE
Broken Building: 21 Fifth Avenue

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#510]
Build 175

21 Fifth Avenue can be rented and entered but you'll end up in void.

[Build175-21FifthAvenue.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071506/Build175-21FifthAvenue.txt)

https://user-images.githubusercontent.com/17579552/131231191-71c07e65-7e3f-485b-8963-cdc99708addf.mp4

**Comment by jhovgaard** [comment]
Fixed in build 177
Requires new savegame
