### ISSUE TITLE
Multiple empty businesses: Employee assignment shows "Option A", "Option B", "Option C"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#512]
Build 175

When having several businesses, some of them empty, the employee assignment list shows "Option A", "Option B" and "Option C" instead of actual business names.
It's impossible to assign an employee to another business.

[Build175-EmployeeOptions.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071572/Build175-EmployeeOptions.txt)

https://user-images.githubusercontent.com/17579552/131232265-38f8f6c9-e883-4a6e-b237-1cdee6129836.mp4

**Comment by jokoho48** [comment]
Fixed in build 181
