### ISSUE TITLE
Recruitment Agency: Rented buildings without business shown as empty list entries

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#513]
Build 175

In the recruitment agency the business selection list shows empty entries for commercial buildings if they don't have a business.

[Build175-RecruitmentAgencyEmptyBusiness.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071578/Build175-RecruitmentAgencyEmptyBusiness.txt)

![grafik](https://user-images.githubusercontent.com/17579552/131232425-f7cf19ad-1b05-4204-90a5-07f7ca6140e8.png)

**Comment by jokoho48** [comment]
Fixed in build 181
