### ISSUE TITLE
Broken Hiding Feature

### ISSUE THREAD

**Issue by CoolGingerGinger** [hovgaardgames/bigambitions-public#514]
Build 153 (Alpha 5)

When leaving 15 Fourth Avenue, El Gato foods (27 Third Street) does not hide properly and windows are still visible. Once you rotate the camera far enough, it will hide appropriately. 

https://user-images.githubusercontent.com/88410729/131267557-11d7f5b1-9fc1-4110-8d60-bb6f04980b92.mp4

**Comment by Gerwanese** [comment]
This is the same as bug #445 and will be fixed once the next build is published.
