### ISSUE TITLE
Long (generated) company names don't have enough space on building layover

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#515]
Build 180

If a company name gets too long and ends up in two lines, the space to shop type and "open" gets too small making it look ugly.

[Build180-MultiLineCompanyName.txt](https://github.com/hovgaardgames/bigambitions-public/files/7079352/Build180-MultiLineCompanyName.txt)

![grafik](https://user-images.githubusercontent.com/17579552/131398718-88f24d2e-db8e-4f9b-93d8-ef18de8c1ecd.png)

**Comment by jhovgaard** [comment]
No longer possible with the 20 character limit.

Fixed in build 194
