### ISSUE TITLE
Shop signboard not hiding when closing phone app

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#516]
Build 181

When opening the BizMan while my shop building is hidden, after closing the app the shop's signboard is "unhidden" (while the shop building itself is still hidden).

[Build181-ShopSignNotHiding.txt](https://github.com/hovgaardgames/bigambitions-public/files/7079693/Build181-ShopSignNotHiding.txt)

https://user-images.githubusercontent.com/17579552/131408010-ccef84e0-1b44-4c67-b258-2589a9ddd59a.mp4

**Comment by jokoho48** [comment]
Fixed in Build 182
