### ISSUE TITLE
BizMan doesn't list SodaCans in Giftshop inventory

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#517]
Build 181

SodaCans are missing from the gift shop inventory even when you have them available and sell them.

[Build181-BizManNoSodaCan.txt](https://github.com/hovgaardgames/bigambitions-public/files/7079753/Build181-BizManNoSodaCan.txt)

https://user-images.githubusercontent.com/17579552/131409356-2971fca8-b44e-42fe-be32-cd288f4e9be7.mp4

**Comment by jokoho48** [comment]
Fixed in Build 182
