### ISSUE TITLE
Tutorial not advancing after running business for 2 days until you leave the shop

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#518]
Build 181

The tutorial doesn't advance after running the gift shop for 2 days.
Once you leave the shop, it will continue.

[Build181-TutorialStuckGiftShop.txt](https://github.com/hovgaardgames/bigambitions-public/files/7079762/Build181-TutorialStuckGiftShop.txt)

![grafik](https://user-images.githubusercontent.com/17579552/131409650-2eaaed29-1a07-40b9-972a-ce4d818283b9.png)

**Comment by jokoho48** [comment]
Fixed in Build 182
