### ISSUE TITLE
Entering No name for a new business doesnt display error message

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#519]
Alpha 5 - Build 181

When creating a new business and you don't type a name into the name box and then click "Start Business" it kicks you back to the image below. Whereas it would make more sense to either display a red error box like when not paying for items, or a red border around the name box.
![image](https://user-images.githubusercontent.com/44293115/131411751-fabfec2a-fca4-4c11-bd56-5298866c2d0e.png)

**Comment by Gerwanese** [comment]
[Build181-NewBusinessNoName.txt](https://github.com/hovgaardgames/bigambitions-public/files/7079855/Build181-NewBusinessNoName.txt)

**Comment by jokoho48** [comment]
Fixed in Build 182
