### ISSUE TITLE
Drive-In Wholesales store: Entering by foot will immediately make you walk out again

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#52]
Build 12
As you can see in the video, when walking into the drive-in wholesales store I walk out again automatically. It's not possible to move in between.
It should either not be possible to enter the store by foot at all or it needs to be possible to stay inside.

https://user-images.githubusercontent.com/17579552/116481762-2849b280-a884-11eb-8a5a-6455705d986e.mp4

**Comment by jhovgaard** [comment]
Fixed in build 49
