### ISSUE TITLE
BizMan: Clearing business name in Settings will shut down business

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#521]
Build 184

When changing the business name in BizMan settings, you can set it to empty (which shouldn't be possible).
This will result in the business shutting down. Once you close and reopen BizMan, you can start a new business.

[Build183-ClearBusinessName.txt](https://github.com/hovgaardgames/bigambitions-public/files/7086565/Build183-ClearBusinessName.txt)

https://user-images.githubusercontent.com/17579552/131568725-f68e7acf-6a58-4b04-b10c-48939659b1cd.mp4

**Comment by jokoho48** [comment]
Fixed in Build 185
