### ISSUE TITLE
Recruitment Agency: Switching off all age filters possible

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#522]
Build 184

At the recruitment agency, you can switch off all age filters (effectively excluding any age).
Also the Primary Skill can be left empty (this might or might not be intended, but I'd guess it's not, as the combobox is shown red without any selection).

[Build184-RecruitmentNoAgeFilter.txt](https://github.com/hovgaardgames/bigambitions-public/files/7093227/Build184-RecruitmentNoAgeFilter.txt)

https://user-images.githubusercontent.com/17579552/131717141-8533a3bf-8711-4b78-97d6-2fafd80bb18b.mp4

**Comment by jokoho48** [comment]
Fixed in Build 185
