### ISSUE TITLE
New map filters behind phone apps on ultrawide screens

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#523]
Build 184

See: https://community.bigambitionsgame.com/t/build-184-map-overlay-issues/416

![grafik](https://user-images.githubusercontent.com/17579552/131720201-e3dd040b-26b8-4060-aa21-21ed94b71bb1.png)

**Comment by jhovgaard** [comment]
@jokoho48 will you add draggable window functionality + increase sort order to above the phone?

**Comment by jokoho48** [comment]
Fixed in Build 193. The general order issue will be fixed in a later update, for now, you can move the element yourself.
