### ISSUE TITLE
Taking a loan before having a job

### ISSUE THREAD

**Issue by LucaFeger** [hovgaardgames/bigambitions-public#524]
In build 184 you can take a loan (max $15.000) before getting a job and working. The objective to reach $300 in the bank can be skipped this way, so I would consider it a bug and not a feature request.
the bug is really self explanatory, so I don't think a video is needed.

**Comment by jhovgaard** [comment]
Changed the objective to "earn $300 from your job salary" instead.

Fixed in build 194
