### ISSUE TITLE
Home icon stays in person view

### ISSUE THREAD

**Issue by LucaFeger** [hovgaardgames/bigambitions-public#525]
Build 184

The voogle maps icon of the home stays after closing voogle maps. 
![grafik](https://user-images.githubusercontent.com/12970930/131723213-7de47e7d-b00e-494e-96ab-47a5572b6ca7.png)

**Comment by jokoho48** [comment]
Fixed in Build 190.

**Comment by jokoho48** [comment]
Fixed in Build 190.
