### ISSUE TITLE
Voogle Maps: 15 Third Avenue outline initially not showing after closing detail dialog

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#530]
Build 185

On Voogle Maps if you click on the building 15 Third Avenue and open the detail dialog, then close the dialog, initially when moving the mouse over the same building again it will not show its outline. Only if you move out and over again, it will show correctly.
This seems to only happen if you are standing in front of the building already, as dragging the map or opening the dialog when the building is not centered will also "fix" the problem.

[Build185-15ThirdAve.txt](https://github.com/hovgaardgames/bigambitions-public/files/7109754/Build185-15ThirdAve.txt)

https://user-images.githubusercontent.com/17579552/132094755-304fb3c4-8ae1-4c99-93ee-5adc26a9c61e.mp4

**Comment by jokoho48** [comment]
Fixed in Build 193.
