### ISSUE TITLE
Car icon not showing anymore on Voogle Maps

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#531]
Build 185

Voogle Maps doesn't show the location of my own cars anymore.

[Build184-CarMadness.txt](https://github.com/hovgaardgames/bigambitions-public/files/7109811/Build184-CarMadness.txt)

![grafik](https://user-images.githubusercontent.com/17579552/132096004-b8a1d83e-537e-4d36-8093-3a41a2eca74c.png)

**Comment by jokoho48** [comment]
Fixed in Build 190.
