### ISSUE TITLE
Employees training: >100% showing in confirmation dialog, employee named "CustomerService"

### ISSUE THREAD

**Issue by Zatoici** [hovgaardgames/bigambitions-public#532]
So it's no longer possible to get your employees to become more than 100% skilled.
Although it's still showing that they will become like that.

And maybe put a employee's **Name** instead of **CustomerService**

Build 184

![Big Ambitions Playtest Screenshot 2021 09 04 - 01 06 00 14](https://user-images.githubusercontent.com/90038819/132099214-81c1b57c-ad25-437b-8ab2-627768bb4889.png)

**Comment by Gerwanese** [comment]
[Build153-OvertrainedEmployee.txt](https://github.com/hovgaardgames/bigambitions-public/files/7110126/Build153-OvertrainedEmployee.txt)

**Comment by jokoho48** [comment]
Fixed in Build 186
