### ISSUE TITLE
Wrong KingSizeBed picking up position

### ISSUE THREAD

**Issue by Zatoici** [hovgaardgames/bigambitions-public#533]
So the position from where you take kingsizebed looks a little off...

Build 184

https://user-images.githubusercontent.com/90038819/132099651-98a0de68-2a45-457b-aad4-4463c13c7dd9.mp4

https://user-images.githubusercontent.com/90038819/132099654-8c0c74e2-9653-4eb0-bc18-6ef4976c8f63.mp4

**Comment by jokoho48** [comment]
has the same cause as #489 and will be fixed with that, so I will close this.
