### ISSUE TITLE
Hotdog is missing in inventory

### ISSUE THREAD

**Issue by Zatoici** [hovgaardgames/bigambitions-public#535]
So, I have Hotdog running in the store, but I don't see them in Inventory meniu

Build 184 

![Big Ambitions Playtest Screenshot 2021 09 03 - 22 25 30 82](https://user-images.githubusercontent.com/90038819/132099936-eef37a04-4fbb-49da-b325-9cf7f099bfef.png)
![Big Ambitions Playtest Screenshot 2021 09 03 - 22 26 10 06](https://user-images.githubusercontent.com/90038819/132099938-64163f90-d7aa-46e7-a831-334119f55294.png)

**Comment by Gerwanese** [comment]
[Build183-MissingHotDogs.txt](https://github.com/hovgaardgames/bigambitions-public/files/7110118/Build183-MissingHotDogs.txt)

**Comment by jokoho48** [comment]
Fixed in Build 186
