### ISSUE TITLE
Pause Graphic showing when using subway selection menu

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#538]
Alpha 6 - Build 187 

When clicking on any subway station to select a destination the pause icon shows up on the screen, although I understand the game is paused whilst in the menu it would make more sense for the animation to not show up.
![image](https://user-images.githubusercontent.com/44293115/132885789-d58fda4b-36e7-46cf-98c0-95c24a94fd4b.png)
[SubwayPause.txt](https://github.com/hovgaardgames/bigambitions-public/files/7145142/SubwayPause.txt)

**Comment by jokoho48** [comment]
Fixed in 188
