### ISSUE TITLE
Missing confirm dialog when discarding items

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#539]
When holding items in hands, you can discard them in two ways, with a "Discard" button and with the red "X" buttons.
![grafik](https://user-images.githubusercontent.com/17579552/134066441-008d1e2b-ebb2-480b-9eb3-374277d51ebe.png)
In both cases there's no confirmation dialog to avoid accidentally discarding items.

**Comment by jhovgaard** [comment]
Fixed in build 225
