### ISSUE TITLE
Clicking a person from inside a car possible causing multiple issues

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#54]
It's possible to click a person while sitting inside a car (which probably isn't intended at all).
It will not trigger an interview, however the clicked-on person will stop walking.
Additionally, the viewing angle changes towards the person and keeps turning towards the person for the rest of the car ride (only way to change it again is by either clicking another person - then you'll always look towards that new person - or parking the car somewhere which will reset the view).

https://user-images.githubusercontent.com/17579552/116482664-e1f55300-a885-11eb-944e-2794d5b7e618.mp4

**Comment by jhovgaard** [comment]
Planned to be fixed with #59

**Comment by jhovgaard** [comment]
Fixed in build 49
