### ISSUE TITLE
Stop working will teleport you to Grey-World

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#546]
Build 208

If you cancel working during your shift, you will end up in the grey "void" world.
The same happens when the shift is ended regularly.

[Build2Build208-WalkWhileWorking.txt](https://github.com/hovgaardgames/bigambitions-public/files/7272321/Build2Build208-WalkWhileWorking.txt)

![grafik](https://user-images.githubusercontent.com/17579552/135733290-1ad75ca7-ca50-4466-8dfb-e04ab47d3ab0.png)

**Comment by jokoho48** [comment]
Fixed in Build 209
