### ISSUE TITLE
Clicking pause button doesn't work anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#548]
Build 208

You can't click the pause button anymore, only using Space works for pausing the game.
I guess it came with the change of the "early preview - not final game" text now growing a but over the pause button.

Resolution: 1920x1200

![grafik](https://user-images.githubusercontent.com/17579552/135734637-60709749-2d00-468b-bf25-241b7c3951c8.png)

**Comment by jokoho48** [comment]
Fixed in Build 209.
