### ISSUE TITLE
Cant walk into 2nd room in first apartment

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#549]
Alpha 6 - Build 209

You click to enter into the room, however, just get stuck in the wall as shown in the image below.
![image](https://user-images.githubusercontent.com/44293115/135762652-76a580a3-341d-4b60-8b7f-527d74f025d4.png)
[Stuckinthewall.txt](https://github.com/hovgaardgames/bigambitions-public/files/7274035/Stuckinthewall.txt)

**Comment by jokoho48** [comment]
Fixed in Build 210
