### ISSUE TITLE
Upcoming tasks not updating in gift shop

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#55]
Build 12 - Alpha 3

When refilling soda cans in stores it updates when you click on the drinks cooler to fill up, but when you leave the store the list unchecks and isnt cleared.

**Comment by adameg2305** [comment]
https://i.adameg.net/PBzSkC.mp4
Video of issue

**Comment by Gerwanese** [comment]
I can confirm this for the gift shop.
In fast food restaurant however it worked correctly.

**Comment by jhovgaard** [comment]
Fixed in Build 54
