### ISSUE TITLE
Schrödingers hand truck in appliance store: Picked up and not picked up at the same time

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#556]
Build 212

When picking up the hand truck, the vehicle box will show but you're not actually holding it. When parking it, another hand truck will appear right over the already existing one.

[Build212-HandtruckFun.txt](https://github.com/hovgaardgames/bigambitions-public/files/7281454/Build212-HandtruckFun.txt)

https://user-images.githubusercontent.com/17579552/135928723-5df770a9-47b9-4a41-88b3-8c1dd9efd37f.mp4

**Comment by jokoho48** [comment]
Fixed in Build 213.
