### ISSUE TITLE
Customers line up on the wrong side of modular cash register

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#563]
Build 212

Customers line up for the new modular cash register on the same side as the worker.
Besides, the position of me working depends on both the cash register rotation and the kitchentable rotation - if I turn around the kitchentable (but not the cash register), I will start working on the other side and facing away from the cash register.

[Build212-CashRegisterWrongLineup.txt](https://github.com/hovgaardgames/bigambitions-public/files/7281666/Build212-CashRegisterWrongLineup.txt)

https://user-images.githubusercontent.com/17579552/135933933-ee0a70f2-a8d1-4791-9f7d-f0e612bb899e.mp4

**Comment by jokoho48** [comment]
Fixed in Build 221
