### ISSUE TITLE
Possible to get stuck in queue of closed shop

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#565]
Build 212

I queued up at the Green Salad after shop was closed already.
Now I'm in queue and can't cancel anymore (cancel button is not working, throwing a NullReferenceException).

[Build212-StuckInSaladShop.txt](https://github.com/hovgaardgames/bigambitions-public/files/7281746/Build212-StuckInSaladShop.txt)

https://user-images.githubusercontent.com/17579552/135936063-cc32a45d-fee9-4533-af12-83654d04546f.mp4

**Comment by jhovgaard** [comment]
Fixed in build 217
