### ISSUE TITLE
Shop tasks broken: Opening hours

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#566]
Build 212

Shop tasks:
- Upcoming task "has no opening hours defined" shown although they are defined

Seems to happen only for GiftShop.

[Build212-ShopTasksBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7281637/Build212-ShopTasksBroken.txt)

![grafik](https://user-images.githubusercontent.com/17579552/135933010-71ed4fe8-a526-4d7f-9869-b2b65bcaa0c8.png)

**Comment by jokoho48** [comment]
Fixed in Build 220
