### ISSUE TITLE
GiftShop tasks broken: CheckoutCounter is out of paperbag although it's not

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#568]
Build 212

Shop tasks:
- Upcoming task "CheckoutCounter is out of paperbag" is greyed out but not removed

[Build212-ShopTasksBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7281637/Build212-ShopTasksBroken.txt)

![grafik](https://user-images.githubusercontent.com/17579552/135933010-71ed4fe8-a526-4d7f-9869-b2b65bcaa0c8.png)

**Comment by jhovgaard** [comment]
Fixed in build 217. You might have to open and close BizMan to re-trigger the task validation.
