### ISSUE TITLE
Shop objectives broken: Buy and place a cash register

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#569]
Build 212

Shop objectives:
- Buy and place a cash register is not fulfilled even when it's done (included in the checkoutcounter)

[Build212-ShopTasksBroken.txt](https://github.com/hovgaardgames/bigambitions-public/files/7281637/Build212-ShopTasksBroken.txt)

![grafik](https://user-images.githubusercontent.com/17579552/135933010-71ed4fe8-a526-4d7f-9869-b2b65bcaa0c8.png)

**Comment by jokoho48** [comment]
Fixed in Build 213.
