### ISSUE TITLE
Shop tasks broken: Jewelry requires CashRegister even if it's there already

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#576]
### Build number

214

### Bug description

The Jewelry got the "requires at least one CashRegister" task although a CashRegister is already placed in the store (on top of a KitchenTable, as it should be). Removing it and placing again didn't help.

### Savegame file

[Build214-BlingysCashRegister.txt](https://github.com/hovgaardgames/bigambitions-public/files/7297536/Build214-BlingysCashRegister.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/136293973-7683bd1b-e621-4a5d-bd5e-487e40a67480.png)

**Comment by jhovgaard** [comment]
Update: I was now able to reproduce. It was actually present.
