### ISSUE TITLE
Liquor Store: No storage for BottleOfWine and Cigar available

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#577]
### Build number

214

### Bug description

The Liquor Store needs storage items for BottleOfWine and Cigar. MetalShelf, RoundedShelf, IndustrialFridge, DrinksFridge all didn't work.

### Steps to reproduce the bug

Items are available in boxes inside the store. Try to place them anywhere in a shelf.

### Savegame file

[Build214-LiquorStore.txt](https://github.com/hovgaardgames/bigambitions-public/files/7297559/Build214-LiquorStore.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/136294403-942b2a36-e6a4-412b-955e-dbf64b961486.png)

**Comment by jhovgaard** [comment]
Added to appliance store #2.

Fixed in build 217
