### ISSUE TITLE
Interior designer outdoors

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#599]
### Build number

223

### Bug description

You can have the interior designer open while you are outside your apartment 

### Steps to reproduce the bug

Start in your apartment at the back wall from the door
Click outside of door
once your player starts walking click on the interior designer button
your character will then walk out of the door while the menu is open

### Savegame file

[Interior Designer outside.txt](https://github.com/hovgaardgames/bigambitions-public/files/7331632/Interior.Designer.outside.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/44293115/136993649-12e3bb7e-9702-4dbc-bf3b-1307699f1086.mp4

**Comment by Gerwanese** [comment]
Still happening for me in build 227.

![grafik](https://user-images.githubusercontent.com/17579552/137201994-19d9e32f-8666-48de-b585-51bbc7eb6568.png)
