### ISSUE TITLE
Wrong course ending time

### ISSUE THREAD

**Issue by LucaFeger** [hovgaardgames/bigambitions-public#6]
When starting a course it shows the time you are finished with learning. The displayed time is always one hour to much. So it shows 19:00 but you are finished at 18:00.

**Comment by jhovgaard** [comment]
Now fixed :)

**Comment by Gerwanese** [comment]
Have to reopen: In build 68, I started the 10 hour course at 06:06, ending time was displayed at 17:00 but I was finished at 16:00 already.


https://user-images.githubusercontent.com/17579552/123314787-4aca1600-d52b-11eb-8f29-a3273f5ecdbb.mp4

**Comment by jhovgaard** [comment]
Fixed in build 70
