### ISSUE TITLE
Game frozen when cancelling course at business school

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#630]
### Build number

230

### Bug description

Click on any of the doors at the business school and then Cancel. Game is frozen.

### Savegame file

[Build227-InsideBusinessSchool.txt](https://github.com/hovgaardgames/bigambitions-public/files/7348562/Build227-InsideBusinessSchool.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/137376875-d5f29e03-4353-41f1-8d9c-3b098af229c8.mp4

**Comment by jhovgaard** [comment]
Fixed in build 231
