### ISSUE TITLE
Can't pick up king-sized bed at Ikea

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#634]
### Build number

232

### Bug description

The king-sized bed can't be picked up anymore at Ikea. Instead you can sleep there.

### Savegame file

[Build227-IkeaSleep.txt](https://github.com/hovgaardgames/bigambitions-public/files/7348904/Build227-IkeaSleep.txt)

### Screenshots or videos

Uploading Big Ambitions Playtest_2021.10.14-21.35.mp4…

**Comment by jhovgaard** [comment]
Fixed in build 233
