### ISSUE TITLE
Buildings not hiding for car

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#66]
Build: 40

The new feature to automatically hide buildings for a free view only works when walking in front of them, but not when driving a car. Only exception I found is the drive-in wholesale store, that building will disappear when necessary.

![grafik](https://user-images.githubusercontent.com/17579552/118715771-5176b680-b824-11eb-893d-dc47bc41ece6.png)

**Comment by jhovgaard** [comment]
Fixed in build 49
