### ISSUE TITLE
Invisible "walls" block way of cars and person

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#67]
Build 40

When driving a car or walking on the street, invisible "walls" will stop the person and cars. It occurs at many places in the city which are always the same - even after reloading, it happens at exact the same locations again.
In the second video you can see that it happens when walking as well - and when I click at the "other side" of the invisible wall, the character will start walking into a completely different direction.
AI cars (not my own driven) also get stuck there, although it seems to only happen if I'm nearby (see screenshot, both marked cars are stuck).

Happens with loaded games as well as with a completely new game.

https://user-images.githubusercontent.com/17579552/118716731-74559a80-b825-11eb-8e18-e423763caa37.mp4

https://user-images.githubusercontent.com/17579552/118717911-f09cad80-b826-11eb-9ec2-e6d159b58c24.mp4

![grafik](https://user-images.githubusercontent.com/17579552/118717173-02318580-b826-11eb-802f-4ba060eb3d48.png)

**Comment by jhovgaard** [comment]
Fixed in build 48
