### ISSUE TITLE
Building only hiding when camera is lower than the roof

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#69]
Build 40 Alpha 4
(Needs new title :) )
When walking and the camera is inside a building then the camera hides, however when the camera is over the top of a building it doesnt hide the building. 
As shown here: https://i.adameg.net/6I8UDx.jpg

**Comment by Gerwanese** [comment]
Can confirm.
Probably also related to #66. I keep them separate though, as I'm not 100% sure (some buildings were hiding when walking, but not when driving).

**Comment by Gerwanese** [comment]
Video highlighting the problem: 

https://user-images.githubusercontent.com/17579552/118730109-585af480-b837-11eb-9022-abf652685bb3.mp4

**Comment by jhovgaard** [comment]
Fixed in build 48
