### ISSUE TITLE
Interview Bubbles showing/hiding malfunctioning

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#70]
Build 40 Alpha 4

When in the map view you still have the interview bubbles showing,https://i.adameg.net/f6sOhr.jpg , but you cant click on them.

**Comment by Gerwanese** [comment]
I could verify that once, although it doesn't happen always.
When walking, theres the opposite problem: Sometimes I get the overlay for interviews, sometimes not (sometimes just for some people but not all).
Once I also got all the interview overlays while driving car.
Behaviour seems to be very erratic.

**Comment by Gerwanese** [comment]
Changed the title to cover the whole problem.

It seems that after loading the game, no bubbles show (or only very occassionally even when walking).
After longer time of running (15+ minutes) more bubbles are showing when walking, but also on the map and while driving.

Here the interview bubbles are shown at the screen corner for people far away:
https://user-images.githubusercontent.com/17579552/118730781-71b07080-b838-11eb-9fed-3e8a70fde23c.mp4
It seems once they were there, when people leave the screen the bubbles will stay there until the person has left the world.

And here the video showing the bubbles while driving (also notice that it's only shown for some people, not for all):
https://user-images.githubusercontent.com/17579552/118730998-c7851880-b838-11eb-897a-46e542854641.mp4

**Comment by jhovgaard** [comment]
Unable to fix in build 49. Will you confirm it's fixed @Gerwanese?

**Comment by Gerwanese** [comment]
It seems the bubbles show up right from the start now, however they don't show for all people (no interviews done yet, so reason can't be that they're interviewed already). If this is intended you can close the bug. If it should show for all people then there's still a bug.

**Comment by Gerwanese** [comment]
In the video of #107 you can see that the bubbles suddenly all showing up and staying at the edge of the screen while people walk away still exists as well.

**Comment by Gerwanese** [comment]
Also see first video of #118 - it's still possible to click the interview button from inside the car.

**Comment by jhovgaard** [comment]
Fixed in build 50 🥳
