### ISSUE TITLE
Several buildings not possible to enter, overlay on wrong building

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#71]
Build 40

The original "home" cannot be entered anymore. Also the restaurant just across the street cannot be entered although I have rented it. Same applies to the rented building on the corner 9th Ave / 3rd Street. The initially rented shop in 9th Avenue besides the bank (not at the street corner but the small one on the other side) appears to be the only own rented building that can be entered.

Another building (three away from the restaurant in 3rd street) gets highlighted, however no interaction is possible there.

https://user-images.githubusercontent.com/17579552/118728327-42980000-b834-11eb-887c-5d643ac6d1c1.mp4

![grafik](https://user-images.githubusercontent.com/17579552/118728605-c18d3880-b834-11eb-9964-c97b446676d4.png)

**Comment by Gerwanese** [comment]
Also the car dealer seems to be affected.
Instead, multiple buildings all over the city get highlighted on mouseover but no interaction possible.

**Comment by Gerwanese** [comment]
In Build 43 I could enter the corner building 9th Ave / 3rd Street again, but the home and the rented restaurant across the street from the home are still inaccessible. Same for the car dealer.
The bank (Jensen Capital) seems to have a wrong coverage area. It's selectable only with the mouse over the green emergency stairs, the rest of the building doesn't react (and even triggers selection of the next building on the sides).

**Comment by jhovgaard** [comment]
Everything should be fixed now in build 48.
