### ISSUE TITLE
All street names displayed as 9th Avenue in Voogle Maps

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#73]
Build 43

All street names in Voogle Maps are shown as 9th Avenue.
![grafik](https://user-images.githubusercontent.com/17579552/119056201-94728e80-b9ca-11eb-83be-c49aeb6d84de.png)

**Comment by daanvangeloven** [comment]
I've run into the same issue

https://i.imgur.com/msHcvg6.jpeg

**Comment by adameg2305** [comment]
Still in Alpha 4, Just to Add as a note

**Comment by jhovgaard** [comment]
Fixed in build 48

**Comment by Gerwanese** [comment]
Reopening.
"Streets" are correct now, "Avenues" are still all "9th".

https://user-images.githubusercontent.com/17579552/120251020-70dbfd80-c280-11eb-83ec-e888a1ead9b1.mp4

**Comment by Gerwanese** [comment]
In build 51 it's back to 9th Avenue for all streets again, so even the partial fix disappeared.

**Comment by jhovgaard** [comment]
Fixed in build 65
