### ISSUE TITLE
Taxi Lights 

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#76]
Alpha 4 - Build 47

Hard to explain, but, When you are walking in front of a taxi and the sun is setting behind the taxi the lights on the taxi either turn on or turn red as shown in this image https://i.adameg.net/m5ci7K.png But when you walk to the side they turn off as shown here: https://i.adameg.net/DL1HYF.png

**Comment by jhovgaard** [comment]
Related to #42
