### ISSUE TITLE
Not enough money at start for apartment rent and buying fridge

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#78]
Alpha 4 - Build 49

When starting a new save and renting the first building (17th Third Street) you then don't have enough money to then complete the next task, more specifically purchasing the fridge and food.

**Comment by Gerwanese** [comment]
Indeed, starting money is not enough for rent plus fridge.
![grafik](https://user-images.githubusercontent.com/17579552/120241252-a96cde80-c262-11eb-8b6e-78f18654dd2f.png)

**Comment by jhovgaard** [comment]
Fixed in build 50
