### ISSUE TITLE
After Working Cant Walk

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#79]
Alpha 4 - Build 49

After working a shift at the El Gato Foods store and your shift ends you get removed from the cash register but you then cant move. 
The animation for walking and running does show.

Once you save the game and leave to main menu, then reload into the game you can then walk freely

**Comment by Gerwanese** [comment]
Verified.
If you still got enough energy you can unlock yourself the next day by starting work and stopping it before end of shift.
If you're out of energy you're in a deadlock.
It does not depend on fast forward or normal speed, also not on opening the work dialog before the shift starts or after - the bug occurs always if you stay until end of working hours.

**Comment by jhovgaard** [comment]
Fixed in build 50
