### ISSUE TITLE
Player not visible on game start

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#82]
Build 49

Right at the start, the player isn't visible because he's hidden behind the first floor wall of a building.
This might be a problem for a new player who isn't used to the game - only seeing a blue arrow but not the person.
I'd recommend to either start in a location with enough space behind or with a different camera angle.
![grafik](https://user-images.githubusercontent.com/17579552/120240758-a6bdb980-c261-11eb-82a0-40e210881f08.png)

**Comment by jhovgaard** [comment]
Fixed in build 61
