### ISSUE TITLE
Picking up hand truck difficult with "manage cargo" overlay

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#85]
Build 49

Due to the automatic "manage cargo" overlay when nearing a hand truck it's a bit difficult to pick it up, especially at night when you can't see well where the truck is to click on it.
![grafik](https://user-images.githubusercontent.com/17579552/120242309-df12c700-c264-11eb-94bd-149df88ed825.png)

**Comment by jhovgaard** [comment]
Fixed in build 51
