### ISSUE TITLE
Hand truck cargo dialog titled "Van Cargo"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#86]
Build: 49

When opening the "manage cargo" dialog for the hand truck, the title of the dialog will show "VAN CARGO".
Same for normal car cargo, it also shows as van cargo.

![grafik](https://user-images.githubusercontent.com/17579552/120242434-2305cc00-c265-11eb-9966-be3302102e66.png)

**Comment by jhovgaard** [comment]
Fixed in build 60
