### ISSUE TITLE
Fridge not placeable in apartment

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#87]
Build 49

After buying the fridge I can't place it in my apartment. When I want to place it I see a grid in front of my entrance door and the fridge is locked to that area but can't be placed.

https://user-images.githubusercontent.com/17579552/120242917-657bd880-c266-11eb-80c8-d8a1090a0902.mp4

**Comment by adameg2305** [comment]
An extension to this, you can place 1 grid-sized item right in front of the doorway but nowhere else. The item is there when you leave and reenter the building, but you can no longer interact with it. 
https://i.adameg.net/w60eyK.png

**Comment by jhovgaard** [comment]
Fixed at some build
