### ISSUE TITLE
Hand truck cargo dialog stays open after picking hand truck

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#89]
Build 49

1. Open the "manage cargo" dialog of a hand truck
2. Pick up the hand truck
3. Now both the "manage cargo" dialog and the "handtruck" window are open at the same time. Removing any item in one of the two will still keep it in the other window.

https://user-images.githubusercontent.com/17579552/120244670-29974200-c26b-11eb-9333-6df47de1b72f.mp4

**Comment by jhovgaard** [comment]
Fixed in build 60
