### ISSUE TITLE
UI and clickable area of "Fast forward" toggle at workplace displaced

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#91]
Build 49

The clickable area for the "Fast forward" toggle at the workplace is moved 50% left from the actual UI element.
As a result, you can't click on the "on" area of the toggle but you can click on the "off" area and also further left of it.

https://user-images.githubusercontent.com/17579552/120245146-93641b80-c26c-11eb-8a36-91267ada6938.mp4

**Comment by jhovgaard** [comment]
Fixed in build 60
