### ISSUE TITLE
Building next to appliance store is apartment and store at same time

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#93]
Build 49

The building next to the appliance store (across the street from starting position) can be rented and will then show the option to open a shop.
It will still be an apartment building however when entering.

https://user-images.githubusercontent.com/17579552/120246239-f7d4aa00-c26f-11eb-939d-64cbae8ebbf3.mp4

**Comment by jhovgaard** [comment]
Fixed in build 55
