### ISSUE TITLE
Deposit for building rental not returned when terminating contract

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#95]
Build 49

When terminating the contract for a building you don't get the deposit back (so it's actually not a deposit but a fee).

https://user-images.githubusercontent.com/17579552/120246610-05d6fa80-c271-11eb-8ce6-bc988f0e7ff0.mp4

**Comment by jhovgaard** [comment]
Fixed in build 67.

Only works for newly rented buildings.
