### ISSUE TITLE
Building info overlays disappear depending on player location

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#96]
Build 49

The video was taken around the corner of the appliance store, where the initial player's apartment is located (across the street from it).
Depending on where the player stands, sometimes the building info overlays work normal and sometimes they just show up for a short moment but disappear right afterwards.

https://user-images.githubusercontent.com/17579552/120246967-23589400-c272-11eb-87c0-6e6a6098b08e.mp4

**Comment by jhovgaard** [comment]
Fixed in some build
