### ISSUE TITLE
"Metal shelf" in wooden table at bank counter

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#99]
Build: 49

At the bank counter theres a steel table "inside" the wooden table. Additionally it twice shows the label "metal shelf".
The metal table can be highlighted but nothing happens on click. The wooden table has the correct handling (seating the player and opening the banking dialog).
![grafik](https://user-images.githubusercontent.com/17579552/120248278-c4e1e480-c276-11eb-9d73-fc8836844819.png)

**Comment by jhovgaard** [comment]
Fixed in build 51

**Comment by adameg2305** [comment]
Needs Reopening, Still here, https://i.adameg.net/gH9QKv.png
